/**
 * Comprehensive Audit Script
 * Quét broken links, meta tags, và accessibility issues
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..', '..');

const CONFIG = {
    excludeDirs: ['node_modules', '.git', 'dist', 'build'],
    fileExtensions: ['.html']
};

function getAllFiles(dir, files = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            if (!CONFIG.excludeDirs.includes(entry.name) && !entry.name.startsWith('.')) {
                getAllFiles(fullPath, files);
            }
        } else if (entry.isFile() && CONFIG.fileExtensions.includes(path.extname(entry.name))) {
            const relPath = path.relative(rootDir, fullPath);
            files.push({ path: fullPath, relPath });
        }
    }
    return files;
}

function checkMetaTags(content, filePath) {
    const issues = [];
    const checks = [
        { pattern: /<meta charset=["']?UTF-8["']?/i, name: 'charset', severity: 'error' },
        { pattern: /<meta name=["']?viewport["']/i, name: 'viewport', severity: 'error' },
        { pattern: /<title>.*<\/title>/i, name: 'title', severity: 'error' },
        { pattern: /<meta name=["']?description["']/i, name: 'description', severity: 'warning' },
        { pattern: /<meta property=["']?og:title["']/i, name: 'og:title', severity: 'warning' },
        { pattern: /<meta property=["']?og:description["']/i, name: 'og:description', severity: 'warning' },
        { pattern: /<meta property=["']?og:image["']/i, name: 'og:image', severity: 'warning' },
        { pattern: /<link rel=["']?canonical["']/i, name: 'canonical', severity: 'info' },
    ];
    for (const check of checks) {
        if (!check.pattern.test(content)) {
            issues.push({ file: filePath, type: 'meta', name: check.name, severity: check.severity, message: `Missing ${check.name}` });
        }
    }
    return issues;
}

function checkAccessibility(content, filePath) {
    const issues = [];
    const checks = [
        { pattern: /<html[^>]*lang=["']/i, name: 'html lang', severity: 'error' },
        { pattern: /<main[^>]*id=["']main["']/i, name: 'main landmark', severity: 'warning' },
        { pattern: /<a[^>]*href=["']#main["']/i, name: 'skip link', severity: 'info' },
    ];
    for (const check of checks) {
        if (!check.pattern.test(content)) {
            issues.push({ file: filePath, type: 'accessibility', name: check.name, severity: check.severity });
        }
    }
    return issues;
}

function checkLinks(content, filePath) {
    const links = [];
    const hrefMatches = content.matchAll(/href=["']([^"']+)["']/gi);
    for (const match of hrefMatches) {
        const url = match[1];
        if (!url.startsWith('http') && !url.startsWith('#') && !url.startsWith('mailto:') && !url.startsWith('tel:')) {
            links.push({ url: url.split('#')[0].split('?')[0], file: filePath });
        }
    }
    return links;
}

function generateReport(summary, issues, brokenLinks) {
    const date = new Date().toISOString().split('T')[0];
    let md = `# 🔍 Comprehensive Audit Report

**Date:** ${date}
**Files Scanned:** ${summary.totalFiles}
**Total Issues:** ${issues.length}

---

## 📊 SUMMARY

| Category | Count |
|----------|-------|
| 🔴 Errors | ${summary.bySeverity.error} |
| 🟡 Warnings | ${summary.bySeverity.warning} |
| ℹ️ Info | ${summary.bySeverity.info} |
| Broken Links | ${brokenLinks.length} |

---

## 🔴 BROKEN LINKS (${brokenLinks.length})

`;
    if (brokenLinks.length > 0) {
        md += '| File | Link |\n|------|------|\n';
        for (const link of brokenLinks.slice(0, 50)) {
            md += `| ${link.file} | ${link.url} |\n`;
        }
    } else {
        md += '**No broken links found!** ✅\n';
    }
    md += `\n---
## 🛠 ACTIONS

- [ ] Fix ${summary.bySeverity.error} errors
- [ ] Review ${summary.bySeverity.warning} warnings
- [ ] Fix ${brokenLinks.length} broken links

*Generated by: comprehensive-audit.js*`;
    return md;
}

// Main
console.log('🔍 Starting Comprehensive Audit...\n');
const htmlFiles = getAllFiles(rootDir);
console.log(`📂 Found ${htmlFiles.length} HTML files\n`);

const allIssues = [];
const allLinks = [];

for (const { path: filePath, relPath } of htmlFiles) {
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        allIssues.push(...checkMetaTags(content, relPath));
        allIssues.push(...checkAccessibility(content, relPath));
        allLinks.push(...checkLinks(content, relPath));
    } catch (error) {
        console.error(`❌ ${relPath}: ${error.message}`);
    }
}

// Summary
const summary = {
    totalFiles: htmlFiles.length,
    bySeverity: { error: 0, warning: 0, info: 0 },
    byType: { meta: 0, accessibility: 0, links: 0 }
};

for (const issue of allIssues) {
    summary.bySeverity[issue.severity]++;
    summary.byType[issue.type]++;
}

// Check broken links
const existingFiles = new Set();
function collectFiles(dir) {
    try {
        const entries = fs.readdirSync(dir, { withFileTypes: true });
        for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);
            if (entry.isDirectory() && !CONFIG.excludeDirs.includes(entry.name)) collectFiles(fullPath);
            else if (entry.isFile()) existingFiles.add(path.relative(rootDir, fullPath).replace(/\\/g, '/'));
        }
    } catch (e) {}
}
collectFiles(rootDir);

const brokenLinks = allLinks.filter(link => {
    const linkPath = link.url.startsWith('/') ? link.url.substring(1) : link.url;
    return !existingFiles.has(linkPath) && !existingFiles.has(linkPath + '.html');
});
summary.brokenLinks = brokenLinks.length;

// Report
const reportMd = generateReport(summary, allIssues, brokenLinks);
const reportDir = path.join(rootDir, 'reports', 'audit');
fs.mkdirSync(reportDir, { recursive: true });
const date = new Date().toISOString().split('T')[0];
fs.writeFileSync(path.join(reportDir, `comprehensive-audit-${date}.md`), reportMd);
fs.writeFileSync(path.join(reportDir, `comprehensive-audit-${date}.json`), JSON.stringify({
    date: new Date().toISOString(), summary, issues: allIssues, brokenLinks
}, null, 2));

console.log('📊 AUDIT SUMMARY\n');
console.log(`Files: ${summary.totalFiles}`);
console.log(`Issues: ${allIssues.length}`);
console.log(`Errors: ${summary.bySeverity.error}`);
console.log(`Warnings: ${summary.bySeverity.warning}`);
console.log(`Info: ${summary.bySeverity.info}`);
console.log(`Broken Links: ${brokenLinks.length}`);
console.log(`\n📄 Report: reports/audit/comprehensive-audit-${date}.md`);
