import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — ADDITIONAL PAGES SMOKE TEST
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 *
 * Coverage: Additional pages not covered by existing smoke tests
 * - Admin: inventory, loyalty, menu, notifications, pos, quality,
 *          raas-overview, roiaas-admin, shifts, suppliers
 * - Landing pages
 *
 * Total: 12 additional pages
 * ═══════════════════════════════════════════════════════════════════════════
 */

const ADDITIONAL_PAGES = [
  // Admin - Additional pages
  { path: '/admin/inventory.html', name: 'Admin Inventory', requiresAuth: true },
  { path: '/admin/loyalty.html', name: 'Admin Loyalty', requiresAuth: true },
  { path: '/admin/menu.html', name: 'Admin Menu Manager', requiresAuth: true },
  { path: '/admin/notifications.html', name: 'Admin Notifications', requiresAuth: true },
  { path: '/admin/pos.html', name: 'Admin POS System', requiresAuth: true },
  { path: '/admin/quality.html', name: 'Admin Quality Control', requiresAuth: true },
  { path: '/admin/raas-overview.html', name: 'Admin RaaS Overview', requiresAuth: true },
  { path: '/admin/roiaas-admin.html', name: 'Admin ROIaaS Admin', requiresAuth: true },
  { path: '/admin/shifts.html', name: 'Admin Shifts', requiresAuth: true },
  { path: '/admin/suppliers.html', name: 'Admin Suppliers', requiresAuth: true },

  // Landing pages (public)
  { path: '/lp.html', name: 'Landing Page', requiresAuth: false },
  { path: '/index.html', name: 'Home Page', requiresAuth: false },
];

test.describe('Smoke Test — Additional Pages Coverage', () => {
  for (const pageConfig of ADDITIONAL_PAGES) {
    test(`${pageConfig.name} (${pageConfig.path}) loads successfully`, async ({ page }) => {
      const errors: string[] = [];

      // Capture JS errors
      page.on('pageerror', (error) => {
        errors.push(error.message);
      });

      // Navigate to page
      await page.goto(pageConfig.path, { waitUntil: 'networkidle', timeout: 15000 });

      // Check HTTP status
      const response = await page.response();
      expect(response?.status()).toBeLessThan(400);

      // Check has title
      const title = await page.title();
      expect(title).toBeTruthy();
      expect(title.length).toBeGreaterThan(0);

      // Check has doctype
      const hasDoctype = await page.evaluate(() => document.doctype !== null);
      expect(hasDoctype).toBeTruthy();

      // Check for broken images
      const brokenImages = await page.evaluate(() => {
        const images = Array.from(document.querySelectorAll('img[src]'));
        return images.filter(img =>
          (img as HTMLImageElement).complete &&
          (img as HTMLImageElement).naturalHeight === 0
        ).length;
      });

      // Allow up to 2 broken images (acceptable threshold)
      expect(brokenImages).toBeLessThanOrEqual(2);

      // Log any JS errors (but don't fail for them)
      if (errors.length > 0) {
        console.log(`JS Errors on ${pageConfig.path}:`, errors.slice(0, 3));
      }

      // Screenshot for visual verification
      await page.screenshot({
        path: `tests/screenshots/additional-${pageConfig.path.replace(/\//g, '-')}.png`,
        fullPage: false
      });
    });
  }

  // ============================================================================
  // INTEGRATION TESTS — UX FEATURES ON PAGES
  // ============================================================================

  test.describe('UX Features Integration', () => {
    test('menu.html has command palette integration', async ({ page }) => {
      await page.goto('/admin/menu.html');

      // Check CSS loaded
      const hasCommandPaletteCSS = await page.evaluate(() => {
        const links = Array.from(document.querySelectorAll('link[rel="stylesheet"]'));
        return links.some(link =>
          link.getAttribute('href')?.includes('command-palette.css')
        );
      });

      expect(hasCommandPaletteCSS).toBeTruthy();
    });

    test('menu.html has notification bell integration', async ({ page }) => {
      await page.goto('/admin/menu.html');

      const hasNotificationBellJS = await page.evaluate(() => {
        const scripts = Array.from(document.querySelectorAll('script[type="module"]'));
        return scripts.some(script =>
          script.getAttribute('src')?.includes('notification-bell.js')
        );
      });

      expect(hasNotificationBellJS).toBeTruthy();
    });

    test('menu.html has theme toggle integration', async ({ page }) => {
      await page.goto('/admin/menu.html');

      const hasThemeToggleCSS = await page.evaluate(() => {
        const links = Array.from(document.querySelectorAll('link[rel="stylesheet"]'));
        return links.some(link =>
          link.getAttribute('href')?.includes('theme-toggle.css')
        );
      });

      expect(hasThemeToggleCSS).toBeTruthy();
    });

    test('menu.html has keyboard shortcuts integration', async ({ page }) => {
      await page.goto('/admin/menu.html');

      const hasKeyboardShortcutsJS = await page.evaluate(() => {
        const scripts = Array.from(document.querySelectorAll('script[type="module"]'));
        return scripts.some(script =>
          script.getAttribute('src')?.includes('keyboard-shortcuts.js')
        );
      });

      expect(hasKeyboardShortcutsJS).toBeTruthy();
    });
  });
});
