/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SA ĐÉC MARKETING HUB — ADDITIONAL PAGES TEST
 * Tests cho các pages còn lại chưa được cover đầy đủ
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 * Coverage Goal: 100% HTML pages tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { test, expect } from '@playwright/test';

/**
 * SECTION: Admin Pages - Additional Coverage
 * Test các admin pages chưa được coverage trong các test files khác
 */
test.describe('Admin Pages - Additional Coverage', () => {
  const ADMIN_PAGES = [
    { path: '/admin/agents.html', name: 'AI Agents', elements: ['agent', 'ai', 'automation'] },
    { path: '/admin/ai-analysis.html', name: 'AI Analysis', elements: ['analysis', 'ai', 'insights'] },
    { path: '/admin/api-builder.html', name: 'API Builder', elements: ['api', 'builder', 'endpoint'] },
    { path: '/admin/approvals.html', name: 'Approvals', elements: ['approval', 'request', 'pending'] },
    { path: '/admin/auth.html', name: 'Authentication', elements: ['auth', 'user', 'permission'] },
    { path: '/admin/binh-phap.html', name: 'Binh Pháp', elements: ['binh-phap', 'strategy', 'tactic'] },
    { path: '/admin/brand-guide.html', name: 'Brand Guide', elements: ['brand', 'guide', 'style'] },
    { path: '/admin/campaigns.html', name: 'Campaigns', elements: ['campaign', 'marketing', 'ads'] },
    { path: '/admin/community.html', name: 'Community', elements: ['community', 'member', 'forum'] },
    { path: '/admin/components-demo.html', name: 'Components Demo', elements: ['component', 'demo', 'ui'] },
    { path: '/admin/content-calendar.html', name: 'Content Calendar', elements: ['content', 'calendar', 'schedule'] },
    { path: '/admin/customer-success.html', name: 'Customer Success', elements: ['customer', 'success', 'support'] },
    { path: '/admin/dashboard.html', name: 'Dashboard', elements: ['dashboard', 'overview', 'stats'] },
    { path: '/admin/deploy.html', name: 'Deploy', elements: ['deploy', 'release', 'version'] },
    { path: '/admin/docs.html', name: 'Documentation', elements: ['docs', 'documentation', 'guide'] },
    { path: '/admin/ecommerce.html', name: 'E-commerce', elements: ['ecommerce', 'shop', 'product'] },
    { path: '/admin/events.html', name: 'Events', elements: ['event', 'calendar', 'schedule'] },
    { path: '/admin/finance.html', name: 'Finance', elements: ['finance', 'revenue', 'expense'] },
    { path: '/admin/hr-hiring.html', name: 'HR & Hiring', elements: ['hr', 'hiring', 'employee'] },
    { path: '/admin/landing-builder.html', name: 'Landing Builder', elements: ['landing', 'builder', 'page'] },
    { path: '/admin/leads.html', name: 'Leads', elements: ['leads', 'crm', 'prospect'] },
    { path: '/admin/legal.html', name: 'Legal', elements: ['legal', 'compliance', 'terms'] },
    { path: '/admin/lms.html', name: 'LMS', elements: ['lms', 'course', 'learning'] },
    { path: '/admin/mvp-launch.html', name: 'MVP Launch', elements: ['mvp', 'launch', 'checklist'] },
    { path: '/admin/onboarding.html', name: 'Onboarding', elements: ['onboarding', 'welcome', 'setup'] },
    { path: '/admin/payments.html', name: 'Payments', elements: ['payment', 'transaction', 'gateway'] },
    { path: '/admin/pipeline.html', name: 'Pipeline', elements: ['pipeline', 'deal', 'sales'] },
    { path: '/admin/pricing.html', name: 'Pricing', elements: ['pricing', 'plan', 'subscription'] },
    { path: '/admin/proposals.html', name: 'Proposals', elements: ['proposal', 'quote', 'estimate'] },
    { path: '/admin/retention.html', name: 'Retention', elements: ['retention', 'churn', 'loyalty'] },
    { path: '/admin/roiaas-admin.html', name: 'ROIaaS Admin', elements: ['roi', 'roiaas', 'analytics'] },
    { path: '/admin/ui-components-demo.html', name: 'UI Components', elements: ['ui', 'component', 'demo'] },
    { path: '/admin/ui-demo.html', name: 'UI Demo', elements: ['ui', 'demo', 'preview'] },
    { path: '/admin/vc-readiness.html', name: 'VC Readiness', elements: ['vc', 'investor', 'pitch'] },
    { path: '/admin/video-workflow.html', name: 'Video Workflow', elements: ['video', 'workflow', 'media'] },
    { path: '/admin/widgets-demo.html', name: 'Widgets Demo', elements: ['widget', 'demo', 'component'] },
    { path: '/admin/workflows.html', name: 'Workflows', elements: ['workflow', 'automation', 'flow'] },
    { path: '/admin/zalo.html', name: 'Zalo OA', elements: ['zalo', 'oa', 'chat'] },
  ];

  // Basic page load tests for all admin pages
  for (const pageConfig of ADMIN_PAGES) {
    test.describe(`${pageConfig.name}`, () => {
      test('page loads successfully', async ({ page: p }) => {
        const response = await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
      });

      test('has valid HTML5 structure', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        // Check DOCTYPE
        const hasDoctype = await p.evaluate(() => {
          const firstChild = document.firstChild;
          return firstChild?.nodeType === 10; // Node.DOCUMENT_TYPE_NODE
        });
        expect(hasDoctype).toBe(true);

        // Check html element exists
        const html = await p.$('html');
        expect(html).toBeTruthy();

        // Check head exists
        const head = await p.$('head');
        expect(head).toBeTruthy();

        // Check body exists
        const body = await p.$('body');
        expect(body).toBeTruthy();
      });

      test('has required meta tags', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        // Viewport meta tag
        const viewport = await p.$('meta[name="viewport"]');
        expect(viewport).toBeTruthy();

        // Charset
        const charset = await p.$('meta[charset]');
        expect(charset).toBeTruthy();

        // Title
        const title = await p.title();
        expect(title).toBeTruthy();
        expect(title.length).toBeGreaterThan(0);
      });

      test('loads without critical JavaScript errors', async ({ page: p }) => {
        const criticalErrors: string[] = [];

        p.on('pageerror', (error) => {
          // Ignore expected errors (Supabase config, etc.)
          if (error.message.includes('supabase')) return;
          if (error.message.includes('__ENV__')) return;
          if (error.message.includes('is not defined')) return;
          if (error.message.includes('CustomElementRegistry')) return;
          if (error.message.includes('Failed to load module')) return;

          criticalErrors.push(error.message);
        });

        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        // Wait a bit for initial JS to load
        await p.waitForTimeout(1000);

        // Allow some non-critical errors (Supabase config, etc. are expected)
        expect(criticalErrors.length).toBeLessThanOrEqual(5);
      });

      test('sidebar component loads', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        // Check for sidebar web component
        const sidebar = await p.$('sadec-sidebar');
        expect(sidebar).toBeTruthy();
      });

      test('main content area exists', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        // Check for main element or main content container
        const main = await p.$('main, [role="main"], .main-content, #main');
        expect(main).toBeTruthy();
      });

      test('responsive viewport meta tag', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        const viewportContent = await p.getAttribute('meta[name="viewport"]', 'content');
        expect(viewportContent).toContain('width=device-width');
        expect(viewportContent).toContain('initial-scale');
      });
    });
  }
});

/**
 * SECTION: Portal Pages Coverage
 */
test.describe('Portal Pages Coverage', () => {
  const PORTAL_PAGES = [
    { path: '/portal/dashboard.html', name: 'Portal Dashboard' },
    { path: '/portal/projects.html', name: 'Projects' },
    { path: '/portal/invoices.html', name: 'Invoices' },
    { path: '/portal/payments.html', name: 'Payments' },
    { path: '/portal/subscriptions.html', name: 'Subscriptions' },
    { path: '/portal/missions.html', name: 'AI Missions' },
    { path: '/portal/ocop-exporter.html', name: 'OCOP Exporter' },
    { path: '/portal/credits.html', name: 'Credits' },
    { path: '/portal/reports.html', name: 'Reports' },
    { path: '/portal/approve.html', name: 'Approve' },
    { path: '/portal/assets.html', name: 'Assets' },
    { path: '/portal/roi-report.html', name: 'ROI Report' },
    { path: '/portal/subscription-plans.html', name: 'Subscription Plans' },
    { path: '/portal/login.html', name: 'Portal Login' },
  ];

  for (const pageConfig of PORTAL_PAGES) {
    test.describe(`${pageConfig.name}`, () => {
      test('page loads successfully', async ({ page: p }) => {
        const response = await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);

        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });

      test('has viewport meta tag', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        const viewport = await p.$('meta[name="viewport"]');
        expect(viewport).toBeTruthy();
      });
    });
  }
});

/**
 * SECTION: Affiliate Pages Coverage
 */
test.describe('Affiliate Pages Coverage', () => {
  const AFFILIATE_PAGES = [
    { path: '/affiliate/dashboard.html', name: 'Affiliate Dashboard' },
    { path: '/affiliate/referrals.html', name: 'Referrals' },
    { path: '/affiliate/commissions.html', name: 'Commissions' },
    { path: '/affiliate/links.html', name: 'Links' },
    { path: '/affiliate/media.html', name: 'Media Kit' },
    { path: '/affiliate/profile.html', name: 'Profile' },
    { path: '/affiliate/settings.html', name: 'Settings' },
  ];

  for (const pageConfig of AFFILIATE_PAGES) {
    test.describe(`${pageConfig.name}`, () => {
      test('page loads successfully', async ({ page: p }) => {
        const response = await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);
      });

      test('has sidebar component', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        const sidebar = await p.$('sadec-sidebar');
        expect(sidebar).toBeTruthy();
      });
    });
  }
});

/**
 * SECTION: F&B Pages Coverage
 */
test.describe('F&B Pages Coverage', () => {
  const FNBPAGES = [
    { path: '/admin/pos.html', name: 'POS System' },
    { path: '/admin/menu.html', name: 'Menu Management' },
    { path: '/admin/inventory.html', name: 'Inventory' },
    { path: '/admin/shifts.html', name: 'Shifts' },
    { path: '/admin/quality.html', name: 'Quality Control' },
    { path: '/admin/suppliers.html', name: 'Suppliers' },
    { path: '/admin/loyalty.html', name: 'Loyalty Program' },
  ];

  for (const pageConfig of FNBPAGES) {
    test.describe(`${pageConfig.name}`, () => {
      test('page loads successfully', async ({ page: p }) => {
        const response = await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
      });

      test('has F&B specific elements', async ({ page: p }) => {
        await p.goto(pageConfig.path, { waitUntil: 'commit', timeout: 30000 });

        // Check for main content
        const main = await p.$('main, [role="main"], .main-content');
        expect(main).toBeTruthy();
      });
    });
  }
});
