/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SA ĐÉC MARKETING HUB — ADDITIONAL PAGES TEST
 * Tests cho các pages còn lại chưa được cover đầy đủ
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 * Coverage Goal: 100% HTML pages tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

import { test, expect } from '@playwright/test';

/**
 * SECTION: Admin Pages - Additional Coverage
 * Test các admin pages chưa được coverage trong các test files khác
 */
test.describe('Admin Pages - Additional Coverage', () => {
  const ADMIN_PAGES = [
    '/admin/ai-analysis.html',
    '/admin/api-builder.html',
    '/admin/auth.html',
    '/admin/binh-phap.html',
    '/admin/campaigns.html',
    '/admin/content-calendar.html',
    '/admin/customer-success.html',
    '/admin/dashboard.html',
    '/admin/deploy.html',
    '/admin/docs.html',
    '/admin/ecommerce.html',
    '/admin/events.html',
    '/admin/finance.html',
    '/admin/hr-hiring.html',
    '/admin/landing-builder.html',
    '/admin/leads.html',
    '/admin/legal.html',
    '/admin/lms.html',
    '/admin/mvp-launch.html',
    '/admin/onboarding.html',
    '/admin/payments.html',
    '/admin/pipeline.html',
    '/admin/pricing.html',
    '/admin/proposals.html',
    '/admin/retention.html',
    '/admin/roiaas-admin.html',
    '/admin/vc-readiness.html',
    '/admin/video-workflow.html',
    '/admin/workflows.html',
    '/admin/zalo.html',
    // Legacy pages (no sidebar)
    '/admin/agents.html',
    '/admin/approvals.html',
    '/admin/brand-guide.html',
    '/admin/community.html',
    '/admin/components-demo.html',
    '/admin/ui-components-demo.html',
    '/admin/ui-demo.html',
    '/admin/widgets-demo.html',
  ];

  for (const pagePath of ADMIN_PAGES) {
    const pageName = pagePath.split('/').pop()?.replace('.html', '') || pagePath;

    test(`✓ ${pageName}`, async ({ page }) => {
      // Single goto with short timeout
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 15000 });

      // Check HTTP status
      expect(response?.status()).toBe(200);

      // Check has HTML
      const html = await page.$('html');
      expect(html).toBeTruthy();

      // Check has body
      const body = await page.$('body');
      expect(body).toBeTruthy();

      // Check has viewport
      const viewport = await page.$('meta[name="viewport"]');
      expect(viewport).toBeTruthy();

      // Check has title
      const title = await page.title();
      expect(title.length).toBeGreaterThan(0);

      // Check has main content
      const main = await page.$('main, [role="main"], .main-content');
      expect(main).toBeTruthy();
    });
  }
});

/**
 * SECTION: Portal Pages Coverage
 */
test.describe('Portal Pages Coverage', () => {
  const PORTAL_PAGES = [
    '/portal/dashboard.html',
    '/portal/projects.html',
    '/portal/invoices.html',
    '/portal/payments.html',
    '/portal/subscriptions.html',
    '/portal/missions.html',
    '/portal/ocop-exporter.html',
    '/portal/credits.html',
    '/portal/reports.html',
    '/portal/approve.html',
    '/portal/assets.html',
    '/portal/roi-report.html',
    '/portal/subscription-plans.html',
    '/portal/login.html',
  ];

  for (const pagePath of PORTAL_PAGES) {
    const pageName = pagePath.split('/').pop()?.replace('.html', '') || pagePath;

    test(`✓ ${pageName}`, async ({ page }) => {
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 15000 });
      expect(response?.status()).toBe(200);

      const html = await page.$('html');
      expect(html).toBeTruthy();

      const viewport = await page.$('meta[name="viewport"]');
      expect(viewport).toBeTruthy();

      const title = await page.title();
      expect(title.length).toBeGreaterThan(0);
    });
  }
});

/**
 * SECTION: Affiliate Pages Coverage
 */
test.describe('Affiliate Pages Coverage', () => {
  const AFFILIATE_PAGES = [
    '/affiliate/dashboard.html',
    '/affiliate/referrals.html',
    '/affiliate/commissions.html',
    '/affiliate/links.html',
    '/affiliate/media.html',
    '/affiliate/profile.html',
    '/affiliate/settings.html',
  ];

  for (const pagePath of AFFILIATE_PAGES) {
    const pageName = pagePath.split('/').pop()?.replace('.html', '') || pagePath;

    test(`✓ ${pageName}`, async ({ page }) => {
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 15000 });
      expect(response?.status()).toBe(200);

      const html = await page.$('html');
      expect(html).toBeTruthy();

      const main = await page.$('main, [role="main"], .main-content');
      expect(main).toBeTruthy();
    });
  }
});

/**
 * SECTION: F&B Pages Coverage
 */
test.describe('F&B Pages Coverage', () => {
  const FNB_PAGES = [
    '/admin/pos.html',
    '/admin/menu.html',
    '/admin/inventory.html',
    '/admin/shifts.html',
    '/admin/quality.html',
    '/admin/suppliers.html',
    '/admin/loyalty.html',
  ];

  for (const pagePath of FNB_PAGES) {
    const pageName = pagePath.split('/').pop()?.replace('.html', '') || pagePath;

    test(`✓ ${pageName}`, async ({ page }) => {
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 15000 });
      expect(response?.status()).toBe(200);

      const main = await page.$('main, [role="main"], .main-content');
      expect(main).toBeTruthy();
    });
  }
});
