import { test, expect } from '@playwright/test';

/**
 * Test Coverage Expansion — Admin Pages Functionality
 * Tests specific functionality for admin pages that were previously untested
 *
 * Generated by: /dev:bug-sprint
 * Date: 2026-03-13
 */

test.describe('Admin Inventory Management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load inventory page without critical errors', async ({ page }) => {
    await expect(page).toHaveURL(/.*inventory\.html/);

    // Check for basic page structure
    await expect(page.locator('body')).toBeVisible();
  });

  test('should have inventory management UI elements', async ({ page }) => {
    // Check for common inventory UI patterns
    const hasTable = page.locator('table').count() > 0;
    const hasCards = page.locator('[class*="card"]').count() > 0;

    // Should have at least one of these
    const hasUI = (await hasTable) || (await hasCards);
    expect(hasUI).toBeTruthy();
  });
});

test.describe('Admin Loyalty Program', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/loyalty.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load loyalty page', async ({ page }) => {
    await expect(page).toHaveURL(/.*loyalty\.html/);
    await expect(page.locator('body')).toBeVisible();
  });

  test('should have loyalty program form elements', async ({ page }) => {
    // Check for form inputs (points, rewards, members)
    const inputs = page.locator('input');
    const count = await inputs.count();
    expect(count).toBeGreaterThan(0);
  });
});

test.describe('Admin Menu Management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/menu.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load menu page', async ({ page }) => {
    await expect(page).toHaveURL(/.*menu\.html/);
    await expect(page.locator('body')).toBeVisible();
  });

  test('should have menu item inputs', async ({ page }) => {
    // Check for menu item inputs (name, price, emoji)
    const hasNameInput = await page.locator('input[id*="name"], input[name*="name"]').count() > 0;
    expect(hasNameInput).toBeTruthy();
  });
});

test.describe('Admin Notifications', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/notifications.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load notifications page', async ({ page }) => {
    await expect(page).toHaveURL(/.*notifications\.html/);
  });

  test('should have notification settings', async ({ page }) => {
    // Check for notification configuration elements
    const hasSettings = await page.locator('input[type="checkbox"], select').count() > 0;
    expect(hasSettings).toBeTruthy();
  });
});

test.describe('Admin POS (Point of Sale)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/pos.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load POS page', async ({ page }) => {
    await expect(page).toHaveURL(/.*pos\.html/);
  });

  test('should have POS interface elements', async ({ page }) => {
    // POS should have product grid or cart elements
    const hasProducts = await page.locator('[class*="product"], [class*="item"]').count() > 0;
    const hasCart = await page.locator('[class*="cart"], [class*="basket"]').count() > 0;

    const hasInterface = hasProducts || hasCart;
    expect(await hasInterface).toBeTruthy();
  });
});

test.describe('Admin Shifts Management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/shifts.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load shifts page', async ({ page }) => {
    await expect(page).toHaveURL(/.*shifts\.html/);
  });

  test('should have shift scheduling elements', async ({ page }) => {
    // Check for date/time inputs for shift scheduling
    const hasDateInput = await page.locator('input[type="date"], input[type="time"]').count() > 0;
    expect(hasDateInput).toBeTruthy();
  });
});

test.describe('Admin Suppliers Management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/suppliers.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load suppliers page', async ({ page }) => {
    await expect(page).toHaveURL(/.*suppliers\.html/);
  });

  test('should have supplier form fields', async ({ page }) => {
    // Check for supplier contact fields
    const hasContactFields = await page.locator('input[id*="phone"], input[id*="email"], input[id*="name"]').count() > 0;
    expect(hasContactFields).toBeTruthy();
  });
});

test.describe('Portal ROI Analytics', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load ROI analytics page', async ({ page }) => {
    await expect(page).toHaveURL(/.*roi-analytics\.html/);
  });

  test('should have analytics dashboard elements', async ({ page }) => {
    // Check for chart/metric containers
    const hasMetrics = await page.locator('[class*="stat"], [class*="metric"], [class*="chart"]').count() > 0;
    expect(hasMetrics).toBeTruthy();
  });
});

test.describe('Portal Subscription Plans', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load subscription plans page', async ({ page }) => {
    await expect(page).toHaveURL(/.*subscription-plans\.html/);
  });

  test('should have pricing elements', async ({ page }) => {
    // Check for pricing display elements
    const hasPricing = await page.locator('[class*="price"], [class*="plan"]').count() > 0;
    expect(hasPricing).toBeTruthy();
  });
});

test.describe('Portal Missions (RaaS)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/missions.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load missions page', async ({ page }) => {
    await expect(page).toHaveURL(/.*missions\.html/);
  });

  test('should have mission list or grid', async ({ page }) => {
    // Check for mission cards or list items
    const hasMissions = await page.locator('[class*="mission"], [class*="task"]').count() > 0;
    expect(hasMissions).toBeTruthy();
  });
});

test.describe('Portal Credits (RaaS)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/credits.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load credits page', async ({ page }) => {
    await expect(page).toHaveURL(/.*credits\.html/);
  });

  test('should display credit balance', async ({ page }) => {
    // Check for credit balance display
    const hasBalance = await page.locator('[class*="balance"], [class*="credit"]').count() > 0;
    expect(hasBalance).toBeTruthy();
  });
});

test.describe('Affiliate Commission Tracking', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/affiliate/commissions.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load commissions page', async ({ page }) => {
    await expect(page).toHaveURL(/.*commissions\.html/);
  });

  test('should have commission data display', async ({ page }) => {
    // Check for commission amount displays
    const hasCommissionData = await page.locator('[class*="commission"], [class*="earn"]').count() > 0;
    expect(hasCommissionData).toBeTruthy();
  });
});

test.describe('Affiliate Media Management', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/affiliate/media.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load media page', async ({ page }) => {
    await expect(page).toHaveURL(/.*media\.html/);
  });

  test('should have media gallery', async ({ page }) => {
    // Check for image gallery or upload area
    const hasMedia = await page.locator('img, [class*="upload"], [class*="gallery"]').count() > 0;
    expect(hasMedia).toBeTruthy();
  });
});

test.describe('Affiliate Profile', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/affiliate/profile.html', { waitUntil: 'domcontentloaded' });
  });

  test('should load profile page', async ({ page }) => {
    await expect(page).toHaveURL(/.*profile\.html/);
  });

  test('should have profile form fields', async ({ page }) => {
    // Check for profile input fields
    const hasProfileFields = await page.locator('input[id*="name"], input[id*="email"]').count() > 0;
    expect(hasProfileFields).toBeTruthy();
  });
});

/**
 * Integration Tests — Cross-page Navigation
 */
test.describe('Navigation Integration Tests', () => {
  test('should navigate from admin dashboard to other admin pages', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

    // Check for navigation links
    const navLinks = page.locator('a[href*="admin/"]');
    const count = await navLinks.count();

    // Dashboard should have navigation to other admin pages
    expect(count).toBeGreaterThan(0);
  });

  test('should have consistent header across admin pages', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });
    const header1 = await page.locator('header, [class*="header"], nav').count();

    await page.goto('/admin/campaigns.html', { waitUntil: 'domcontentloaded' });
    const header2 = await page.locator('header, [class*="header"], nav').count();

    // Both pages should have header elements
    expect(header1).toBeGreaterThan(0);
    expect(header2).toBeGreaterThan(0);
  });
});

/**
 * Accessibility Tests — Basic Checks
 */
test.describe('Accessibility Tests — Admin Pages', () => {
  const adminPages = [
    '/admin/inventory.html',
    '/admin/loyalty.html',
    '/admin/menu.html',
    '/admin/notifications.html',
  ];

  for (const pagePath of adminPages) {
    test(`${pagePath} should have accessible forms`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded' });

      // Check that inputs have associated labels or aria-labels
      const inputs = page.locator('input:not([type="hidden"]), textarea, select');
      const count = await inputs.count();

      for (let i = 0; i < Math.min(count, 5); i++) {
        const input = inputs.nth(i);
        const hasLabel = await input.evaluate(el => {
          // Check for aria-label
          if (el.getAttribute('aria-label')) return true;
          // Check for id and associated label
          const id = el.id;
          if (id && document.querySelector(`label[for="${id}"]`)) return true;
          // Check for parent label
          return el.closest('label') !== null;
        });

        // Not all inputs need labels (some might be buttons, etc.)
        // This is a soft check - just log if missing
        if (!hasLabel) {
          console.log(`Input at index ${i} in ${pagePath} may be missing label`);
        }
      }
    });
  }
});
