import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — ADMIN PAGES COVERAGE TEST
 * Test coverage cho các admin pages chưa được test đầy đủ
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-14
 * Coverage Goal: 100% admin pages tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

/**
 * ADMIN PAGES - Functional Tests
 * Test các admin pages với functional checks
 */
test.describe('Admin Pages - Functional Coverage', () => {
  const ADMIN_PAGES = [
    { path: '/admin/features-demo.html', name: 'Features Demo', expectedElements: ['feature', 'demo', 'component'] },
    { path: '/admin/features-demo-2027.html', name: 'Features Demo 2027', expectedElements: ['feature', 'demo', '2027'] },
    { path: '/admin/components-demo.html', name: 'Components Demo', expectedElements: ['component', 'ui', 'button'] },
    { path: '/admin/ui-components-demo.html', name: 'UI Components Demo', expectedElements: ['ui', 'component', 'demo'] },
    { path: '/admin/ux-components-demo.html', name: 'UX Components Demo', expectedElements: ['ux', 'component', 'interaction'] },
    { path: '/admin/ui-demo.html', name: 'UI Demo', expectedElements: ['ui', 'demo', 'interface'] },
    { path: '/admin/quality.html', name: 'Quality Control', expectedElements: ['quality', 'control', 'check'] },
    { path: '/admin/notifications.html', name: 'Admin Notifications', expectedElements: ['notification', 'alert', 'message'] },
    { path: '/admin/inventory.html', name: 'Inventory', expectedElements: ['inventory', 'stock', 'product'] },
    { path: '/admin/agents.html', name: 'AI Agents', expectedElements: ['agent', 'ai', 'automation'] },
  ];

  for (const page of ADMIN_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];
        p.on('pageerror', (error) => {
          // Ignore expected errors ( Supabase config, env vars not loaded in test)
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        // Allow up to 3 non-critical errors
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });

        // Check DOCTYPE
        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);

        // Check html lang
        const htmlLang = await p.getAttribute('html', 'lang');
        expect(htmlLang).toBeTruthy();

        // Check title
        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });

      test('has required meta tags', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });

        // Viewport
        const viewport = await p.getAttribute('meta[name="viewport"]', 'content');
        expect(viewport).toBeTruthy();

        // Charset
        const charset = await p.querySelector('meta[charset]');
        expect(charset).toBeTruthy();
      });
    });
  }
});

/**
 * FEATURES DEMO - Specific Tests
 */
test.describe('Features Demo Pages', () => {
  test('features-demo loads with widgets', async ({ page }) => {
    const response = await page.goto('/admin/features-demo.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);

    // Check for widget containers
    const widgetCount = await page.locator('[class*="widget"], [data-widget]').count();
    expect(widgetCount).toBeGreaterThan(0);
  });

  test('features-demo-2027 has advanced features', async ({ page }) => {
    await page.goto('/admin/features-demo-2027.html', { waitUntil: 'domcontentloaded' });

    // Check for 2027-specific features
    const hasAdvancedFeatures = await page.locator('[class*="advanced"], [class*="ai-"], [class*="smart-"]').count();
    expect(hasAdvancedFeatures).toBeGreaterThan(0);
  });

  test('components-demo has UI components', async ({ page }) => {
    await page.goto('/admin/components-demo.html', { waitUntil: 'domcontentloaded' });

    // Check for component examples
    const hasButtons = await page.locator('button').count();
    const hasInputs = await page.locator('input').count();
    const hasCards = await page.locator('[class*="card"]').count();

    expect(hasButtons + hasInputs + hasCards).toBeGreaterThan(0);
  });
});

/**
 * UI/UX DEMO PAGES - Specific Tests
 */
test.describe('UI/UX Demo Pages', () => {
  test('ui-components-demo loads', async ({ page }) => {
    const response = await page.goto('/admin/ui-components-demo.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('ux-components-demo loads', async ({ page }) => {
    const response = await page.goto('/admin/ux-components-demo.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('ui-demo has interactive elements', async ({ page }) => {
    await page.goto('/admin/ui-demo.html', { waitUntil: 'domcontentloaded' });

    // Check for interactive UI elements
    const hasInteractiveElements = await page.locator('button, input, a, [role="button"]').count();
    expect(hasInteractiveElements).toBeGreaterThan(0);
  });
});

/**
 * INVENTORY MANAGEMENT - Specific Tests
 */
test.describe('Inventory Management', () => {
  test('loads inventory page', async ({ page }) => {
    const response = await page.goto('/admin/inventory.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has inventory table', async ({ page }) => {
    await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded' });

    // Check for inventory table
    const hasTable = await page.locator('table').count();
    expect(hasTable).toBeGreaterThan(0);

    // Check for product-related elements
    const hasProductElements = await page.locator('[class*="product"], [class*="item"], [class*="sku"]').count();
    expect(hasProductElements).toBeGreaterThan(0);
  });

  test('has inventory controls', async ({ page }) => {
    await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded' });

    // Check for inventory action buttons
    const hasActions = await page.locator('button:has-text("Add"), button:has-text("Edit"), button:has-text("Delete"), button:has-text("Export")').count();
    expect(hasActions).toBeGreaterThan(0);
  });
});

/**
 * QUALITY CONTROL - Specific Tests
 */
test.describe('Quality Control', () => {
  test('loads quality page', async ({ page }) => {
    const response = await page.goto('/admin/quality.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has quality metrics', async ({ page }) => {
    await page.goto('/admin/quality.html', { waitUntil: 'domcontentloaded' });

    // Check for quality metrics/KPIs
    const hasMetrics = await page.locator('[class*="metric"], [class*="kpi"], [class*="score"]').count();
    expect(hasMetrics).toBeGreaterThan(0);
  });

  test('has quality controls', async ({ page }) => {
    await page.goto('/admin/quality.html', { waitUntil: 'domcontentloaded' });

    // Check for quality control inputs
    const hasControls = await page.locator('input[type="checkbox"], input[type="radio"], select').count();
    expect(hasControls).toBeGreaterThan(0);
  });
});

/**
 * AI AGENTS - Specific Tests
 */
test.describe('AI Agents Management', () => {
  test('loads agents page', async ({ page }) => {
    const response = await page.goto('/admin/agents.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has agent cards', async ({ page }) => {
    await page.goto('/admin/agents.html', { waitUntil: 'domcontentloaded' });

    // Check for agent cards/list
    const hasAgentCards = await page.locator('[class*="agent"], [class*="card"]').count();
    expect(hasAgentCards).toBeGreaterThan(0);
  });

  test('has agent controls', async ({ page }) => {
    await page.goto('/admin/agents.html', { waitUntil: 'domcontentloaded' });

    // Check for agent action buttons
    const hasControls = await page.locator('button:has-text("Enable"), button:has-text("Disable"), button:has-text("Configure"), button:has-text("Create")').count();
    expect(hasControls).toBeGreaterThan(0);
  });
});

/**
 * ACCESSIBILITY - Quick Checks
 */
test.describe('Admin Accessibility', () => {
  const KEY_PAGES = [
    '/admin/dashboard.html',
    '/admin/features-demo.html',
    '/admin/components-demo.html',
    '/admin/inventory.html',
    '/admin/quality.html',
  ];

  for (const pagePath of KEY_PAGES) {
    test(`${pagePath} has accessible labels`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });

      // Check for role attributes
      const hasMainRole = await page.locator('[role="main"], main').count();
      const hasNavRole = await page.locator('[role="navigation"], nav').count();

      // At least one semantic element should exist
      expect(hasMainRole + hasNavRole).toBeGreaterThan(0);
    });
  }
});

/**
 * RESPONSIVE - Mobile Viewport Tests
 */
test.describe('Admin Responsive', () => {
  test('admin features-demo is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 }); // iPhone 12 mini
    const response = await page.goto('/admin/features-demo.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);
  });

  test('admin components-demo is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 768, height: 1024 }); // iPad
    const response = await page.goto('/admin/components-demo.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);
  });

  test('admin inventory is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 }); // iPhone 12/13 Pro
    const response = await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);
  });
});

/**
 * PERFORMANCE - Load Time Tests
 */
test.describe('Admin Performance', () => {
  const PAGES = [
    '/admin/features-demo.html',
    '/admin/components-demo.html',
    '/admin/inventory.html',
  ];

  for (const pagePath of PAGES) {
    test(`${pagePath} loads within 3 seconds`, async ({ page }) => {
      const startTime = Date.now();
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });
      const loadTime = Date.now() - startTime;

      expect(response?.status()).toBe(200);
      expect(loadTime).toBeLessThan(3000); // 3 second threshold
    });
  }
});
