import { test, expect } from '@playwright/test';

/**
 * Admin Finance Page Tests
 * Tests for /admin/finance.html
 *
 * Generated by: /dev-bug-sprint "Viet tests cover untested pages"
 * Date: 2026-03-13
 */

test.describe('Admin Finance - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
      errors.push(error.message);
    });

    const response = await page.goto('/admin/finance.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });

  test('should have valid HTML structure', async ({ page }) => {
    await page.goto('/admin/finance.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const hasDoctype = await page.evaluate(() => document.doctype?.name === 'html');
    expect(hasDoctype).toBeTruthy();
  });

  test('should have required meta tags', async ({ page }) => {
    await page.goto('/admin/finance.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const title = await page.title();
    expect(title.length).toBeGreaterThan(5);

    const viewport = await page.getAttribute('meta[name="viewport"]', 'content');
    expect(viewport).toBeTruthy();
  });
});

test.describe('Admin Finance - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/finance.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display finance dashboard sections', async ({ page }) => {
    const mainContent = page.locator('main, [role="main"]');
    await expect(mainContent).toBeVisible();

    // Finance sections should exist
    const sections = page.locator('section, [class*="finance"], [class*="revenue"]');
    const count = await sections.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have revenue metrics display', async ({ page }) => {
    const metrics = page.locator('[class*="metric"], [class*="kpi"], [class*="stat"]');
    const count = await metrics.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have financial charts', async ({ page }) => {
    const charts = page.locator('canvas, svg, [class*="chart"], [id*="chart"]');
    const count = await charts.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have data tables for transactions', async ({ page }) => {
    const tables = page.locator('table, [class*="data-table"], [class*="transaction"]');
    const count = await tables.count();

    if (count > 0) {
      const firstTable = tables.first();
      await expect(firstTable).toBeVisible();
    }
  });
});

test.describe('Admin Finance - Responsive', () => {
  const viewports = [
    { name: 'mobile', width: 375, height: 667 },
    { name: 'tablet', width: 768, height: 1024 },
    { name: 'desktop', width: 1440, height: 900 },
  ];

  for (const vp of viewports) {
    test(`should render correctly on ${vp.name} (${vp.width}x${vp.height})`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height });
      await page.goto('/admin/finance.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

      const mainContent = page.locator('main, [role="main"]');
      await expect(mainContent).toBeVisible();
    });
  }
});
