import { test, expect } from '@playwright/test';

/**
 * Admin HR-Hiring & LMS Tests
 * Tests for /admin/hr-hiring.html and /admin/lms.html
 *
 * Generated by: /dev-bug-sprint "Viet tests cover untested pages"
 * Date: 2026-03-13
 */

// ===== HR-HIRING TESTS =====
test.describe('Admin HR-Hiring - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      errors.push(error.message);
    });

    const response = await page.goto('/admin/hr-hiring.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });

  test('should have valid structure', async ({ page }) => {
    await page.goto('/admin/hr-hiring.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const hasDoctype = await page.evaluate(() => document.doctype?.name === 'html');
    expect(hasDoctype).toBeTruthy();
  });
});

test.describe('Admin HR-Hiring - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/hr-hiring.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display HR sections', async ({ page }) => {
    const mainContent = page.locator('main, [role="main"]');
    await expect(mainContent).toBeVisible();

    const sections = page.locator('section, [class*="hr"], [class*="hiring"], [class*="candidate"]');
    const count = await sections.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have job listings table', async ({ page }) => {
    const tables = page.locator('table, [class*="data-table"], [class*="job-table"]');
    const count = await tables.count();

    if (count > 0) {
      const firstTable = tables.first();
      await expect(firstTable).toBeVisible();
    }
  });

  test('should have hire/add buttons', async ({ page }) => {
    const buttons = page.locator('button, [class*="btn"], [class*="action"]');
    const count = await buttons.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });
});

// ===== LMS TESTS =====
test.describe('Admin LMS - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      errors.push(error.message);
    });

    const response = await page.goto('/admin/lms.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });
});

test.describe('Admin LMS - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/lms.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display LMS dashboard', async ({ page }) => {
    const mainContent = page.locator('main, [role="main"]');
    await expect(mainContent).toBeVisible();

    const lmsElements = page.locator('[class*="lms"], [class*="course"], [class*="learning"]');
    const count = await lmsElements.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have course list', async ({ page }) => {
    const courses = page.locator('[class*="course-card"], [class*="module"], [class*="lesson"]');
    const count = await courses.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have progress indicators', async ({ page }) => {
    const progressElements = page.locator('[class*="progress"], [class*="bar"], [class*="completion"]');
    const count = await progressElements.count();
    expect(count).toBeGreaterThanOrEqual(0);
  });
});

// ===== RESPONSIVE TESTS =====
test.describe('HR-Hiring & LMS - Responsive', () => {
  const pages = [
    { path: '/admin/hr-hiring.html', name: 'HR-Hiring' },
    { path: '/admin/lms.html', name: 'LMS' },
  ];

  const viewports = [
    { name: 'mobile', width: 375, height: 667 },
    { name: 'tablet', width: 768, height: 1024 },
  ];

  for (const pg of pages) {
    for (const vp of viewports) {
      test(`${pg.name} should render on ${vp.name}`, async ({ page }) => {
        await page.setViewportSize({ width: vp.width, height: vp.height });
        await page.goto(pg.path, { waitUntil: 'domcontentloaded', timeout: 15000 });
        const mainContent = page.locator('main, [role="main"]');
        await expect(mainContent).toBeVisible();
      });
    }
  }
});
