import { test, expect } from '@playwright/test';

/**
 * Admin Inventory & POS Tests
 * Tests for /admin/inventory.html and /admin/pos.html
 *
 * Generated by: /dev-bug-sprint "Viet tests cover untested pages"
 * Date: 2026-03-13
 */

// ===== INVENTORY TESTS =====
test.describe('Admin Inventory - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      errors.push(error.message);
    });

    const response = await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });

  test('should have valid structure', async ({ page }) => {
    await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const hasDoctype = await page.evaluate(() => document.doctype?.name === 'html');
    expect(hasDoctype).toBeTruthy();
  });
});

test.describe('Admin Inventory - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display inventory sections', async ({ page }) => {
    const mainContent = page.locator('main, [role="main"]');
    await expect(mainContent).toBeVisible();

    const sections = page.locator('section, [class*="inventory"], [class*="stock"]');
    const count = await sections.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have inventory data table', async ({ page }) => {
    const tables = page.locator('table, [class*="data-table"], [class*="inventory-table"]');
    const count = await tables.count();

    if (count > 0) {
      const firstTable = tables.first();
      await expect(firstTable).toBeVisible();
    }
  });

  test('should have add/manage item buttons', async ({ page }) => {
    const buttons = page.locator('button, [class*="btn"], [class*="action"]');
    const count = await buttons.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });
});

// ===== POS TESTS =====
test.describe('Admin POS - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      errors.push(error.message);
    });

    const response = await page.goto('/admin/pos.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });
});

test.describe('Admin POS - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/admin/pos.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display POS interface', async ({ page }) => {
    const mainContent = page.locator('main, [role="main"]');
    await expect(mainContent).toBeVisible();

    const posElements = page.locator('[class*="pos"], [class*="register"], [class*="checkout"]');
    const count = await posElements.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have product grid', async ({ page }) => {
    const productGrid = page.locator('[class*="product"], [class*="item-grid"]');
    const isVisible = await productGrid.isVisible();
    expect(isVisible).toBeTruthy();
  });

  test('should have cart/order summary', async ({ page }) => {
    const cartElements = page.locator('[class*="cart"], [class*="order"], [class*="basket"]');
    const count = await cartElements.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });
});

// ===== RESPONSIVE TESTS FOR BOTH =====
test.describe('Inventory & POS - Responsive', () => {
  const pages = [
    { path: '/admin/inventory.html', name: 'Inventory' },
    { path: '/admin/pos.html', name: 'POS' },
  ];

  const viewports = [
    { name: 'mobile', width: 375, height: 667 },
    { name: 'tablet', width: 768, height: 1024 },
  ];

  for (const pg of pages) {
    for (const vp of viewports) {
      test(`${pg.name} should render on ${vp.name}`, async ({ page }) => {
        await page.setViewportSize({ width: vp.width, height: vp.height });
        await page.goto(pg.path, { waitUntil: 'domcontentloaded', timeout: 15000 });
        const mainContent = page.locator('main, [role="main"]');
        await expect(mainContent).toBeVisible();
      });
    }
  }
});
