import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — AUTH & CORE PAGES TEST
 * Tests cho authentication và core functionality
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 * ═══════════════════════════════════════════════════════════════════════════
 */

test.describe('Auth Pages', () => {
    test.describe('Login Page', () => {
        test('should load login page with form', async ({ page }) => {
            await page.goto('/login.html', { waitUntil: 'domcontentloaded' });

            // Has title
            const title = await page.title();
            expect(title.length).toBeGreaterThan(0);

            // Has login form
            const emailInput = page.locator('input[type="email"], input[name="email"]');
            await expect(emailInput).toBeVisible();

            const passwordInput = page.locator('input[type="password"], input[name="password"]');
            await expect(passwordInput).toBeVisible();

            // Has submit button
            const submitBtn = page.locator('button[type="submit"], input[type="submit"]');
            await expect(submitBtn).toBeVisible();
        });

        test('should have forgot password link', async ({ page }) => {
            await page.goto('/login.html', { waitUntil: 'domcontentloaded' });

            const forgotLink = page.locator('a[href*="forgot-password"]');
            await expect(forgotLink).toBeVisible();
        });

        test('should have register link', async ({ page }) => {
            await page.goto('/login.html', { waitUntil: 'domcontentloaded' });

            const registerLink = page.locator('a[href*="register"], a[href*="sign-up"]');
            await expect(registerLink).toBeVisible();
        });
    });

    test.describe('Register Page', () => {
        test('should load register page with form', async ({ page }) => {
            await page.goto('/register.html', { waitUntil: 'domcontentloaded' });

            // Has title
            const title = await page.title();
            expect(title.length).toBeGreaterThan(0);

            // Has name input
            const nameInput = page.locator('input[name="name"], input[name="full_name"]');
            await expect(nameInput).toBeVisible();

            // Has email input
            const emailInput = page.locator('input[type="email"], input[name="email"]');
            await expect(emailInput).toBeVisible();

            // Has password input
            const passwordInput = page.locator('input[type="password"]');
            await expect(passwordInput).toHaveCount(2); // Password + confirm
        });
    });

    test.describe('Forgot Password Page', () => {
        test('should load forgot password page', async ({ page }) => {
            await page.goto('/forgot-password.html', { waitUntil: 'domcontentloaded' });

            // Has title
            const title = await page.title();
            expect(title.length).toBeGreaterThan(0);

            // Has email input
            const emailInput = page.locator('input[type="email"]');
            await expect(emailInput).toBeVisible();

            // Has submit button
            const submitBtn = page.locator('button[type="submit"]');
            await expect(submitBtn).toBeVisible();
        });
    });

    test.describe('Portal Login', () => {
        test('should load portal login page', async ({ page }) => {
            await page.goto('/portal/login.html', { waitUntil: 'domcontentloaded' });

            const title = await page.title();
            expect(title.length).toBeGreaterThan(0);

            const emailInput = page.locator('input[type="email"]');
            await expect(emailInput).toBeVisible();
        });
    });
});

test.describe('Core Landing Pages', () => {
    test('homepage loads with content', async ({ page }) => {
        await page.goto('/index.html', { waitUntil: 'domcontentloaded' });

        // Has title
        const title = await page.title();
        expect(title.toLowerCase()).toContain('mekong') || expect(title.toLowerCase()).toContain('marketing');

        // Has main content
        const main = page.locator('main, .main-content, #app');
        await expect(main).toBeVisible();

        // Has navigation
        const nav = page.locator('nav, .nav, .navigation');
        await expect(nav).toBeVisible();

        // Has footer
        const footer = page.locator('footer, .footer');
        await expect(footer).toBeVisible();
    });

    test('landing page (lp.html) loads', async ({ page }) => {
        await page.goto('/lp.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);

        // Has hero section
        const hero = page.locator('.hero, .hero-section, header');
        await expect(hero).toBeVisible();

        // Has CTA button
        const cta = page.locator('button, a[href*="#"], .cta, .btn');
        await expect(cta.first()).toBeVisible();
    });

    test('offline page loads', async ({ page }) => {
        await page.goto('/offline.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);

        // Has offline message
        const content = await page.content();
        expect(content.toLowerCase()).toContain('offline') || expect(content.toLowerCase()).toContain('connection');
    });
});

test.describe('Legal Pages', () => {
    test('terms page loads', async ({ page }) => {
        await page.goto('/terms.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.toLowerCase()).toContain('term');

        const content = await page.content();
        expect(content.length).toBeGreaterThan(100);
    });

    test('privacy page loads', async ({ page }) => {
        await page.goto('/privacy.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.toLowerCase()).toContain('privac');

        const content = await page.content();
        expect(content.length).toBeGreaterThan(100);
    });
});

test.describe('Affiliate Pages', () => {
    test('affiliate dashboard loads (auth redirect expected)', async ({ page }) => {
        await page.goto('/affiliate/dashboard.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);

        // Has affiliate branding
        const content = await page.content();
        expect(content.toLowerCase()).toContain('affiliate');
    });

    test('affiliate referrals page loads', async ({ page }) => {
        await page.goto('/affiliate/referrals.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);
    });

    test('affiliate commissions page loads', async ({ page }) => {
        await page.goto('/affiliate/commissions.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);
    });

    test('affiliate profile page loads', async ({ page }) => {
        await page.goto('/affiliate/profile.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);
    });
});

test.describe('Verify Email Page', () => {
    test('verify email page loads', async ({ page }) => {
        await page.goto('/verify-email.html', { waitUntil: 'domcontentloaded' });

        const title = await page.title();
        expect(title.length).toBeGreaterThan(0);

        // Has verification message
        const content = await page.content();
        expect(content.toLowerCase()).toContain('verif') || expect(content.toLowerCase()).toContain('email');
    });
});
