import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — COMPREHENSIVE PAGE COVERAGE TEST
 * Bổ sung tests cho các pages chưa được coverage đầy đủ
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 * Coverage Goal: 100% HTML pages tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

/**
 * SECTION 1: Admin Pages - Functional Tests
 * Test các admin pages với functional checks chi tiết
 */
test.describe('Admin Pages - Functional Coverage', () => {
  const ADMIN_PAGES = [
    { path: '/admin/inventory.html', name: 'Inventory Management', expectedElements: ['inventory', 'stock', 'product'] },
    { path: '/admin/loyalty.html', name: 'Loyalty Program', expectedElements: ['loyalty', 'points', 'rewards'] },
    { path: '/admin/menu.html', name: 'Menu Manager', expectedElements: ['menu', 'items', 'category'] },
    { path: '/admin/notifications.html', name: 'Notifications', expectedElements: ['notification', 'alert', 'message'] },
    { path: '/admin/pos.html', name: 'POS System', expectedElements: ['pos', 'sale', 'checkout'] },
    { path: '/admin/quality.html', name: 'Quality Control', expectedElements: ['quality', 'control', 'check'] },
    { path: '/admin/raas-overview.html', name: 'RaaS Overview', expectedElements: ['raas', 'overview', 'dashboard'] },
    { path: '/admin/roiaas-admin.html', name: 'ROIaaS Admin', expectedElements: ['roi', 'analytics', 'dashboard'] },
    { path: '/admin/shifts.html', name: 'Shifts Management', expectedElements: ['shift', 'schedule', 'employee'] },
    { path: '/admin/suppliers.html', name: 'Suppliers', expectedElements: ['supplier', 'vendor', 'contact'] },
  ];

  for (const page of ADMIN_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];
        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(0);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });

        // Check DOCTYPE
        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);

        // Check html lang
        const htmlLang = await p.getAttribute('html', 'lang');
        expect(htmlLang).toBeTruthy();

        // Check title
        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
        expect(title.toLowerCase()).toContain(page.name.toLowerCase().split(' ')[0]);
      });

      test('has required meta tags', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });

        // Viewport
        const viewport = await p.getAttribute('meta[name="viewport"]', 'content');
        expect(viewport).toBeTruthy();

        // Charset
        const charset = await p.querySelector('meta[charset]');
        expect(charset).toBeTruthy();

        // Description (optional but recommended)
        const description = await p.getAttribute('meta[name="description"]', 'content');
        // Not failing if missing, just logging
        if (!description) {
          console.log(`Missing description on ${page.path}`);
        }
      });

      test('is responsive on mobile', async ({ page: p }) => {
        await p.setViewportSize({ width: 375, height: 812 });
        const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });
        expect(response?.status()).toBe(200);
      });

      test('has main landmark for accessibility', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });
        const hasMain = await p.evaluate(() => document.querySelector('main, [role="main"]') !== null);
        expect(hasMain).toBe(true);
      });
    });
  }
});

/**
 * SECTION 2: Portal Pages - Functional Tests
 */
test.describe('Portal Pages - Functional Coverage', () => {
  const PORTAL_PAGES = [
    { path: '/portal/ocop-catalog.html', name: 'OCOP Catalog', expectedElements: ['ocop', 'catalog', 'products'] },
    { path: '/portal/roi-report.html', name: 'ROI Report', expectedElements: ['roi', 'report', 'analytics'] },
    { path: '/portal/roiaas-dashboard.html', name: 'ROIaaS Dashboard', expectedElements: ['dashboard', 'roi', 'metrics'] },
    { path: '/portal/roiaas-onboarding.html', name: 'ROIaaS Onboarding', expectedElements: ['onboarding', 'setup', 'welcome'] },
    { path: '/portal/subscription-plans.html', name: 'Subscription Plans', expectedElements: ['subscription', 'pricing', 'plan'] },
    { path: '/portal/notifications.html', name: 'Notifications', expectedElements: ['notification', 'alert'] },
    { path: '/portal/roi-analytics.html', name: 'ROI Analytics', expectedElements: ['analytics', 'roi', 'metrics'] },
  ];

  for (const page of PORTAL_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads successfully', async ({ page: p }) => {
        const errors: string[] = [];
        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (/is not defined/.test(error.message) && /Auth|createDemo/.test(error.message)) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(0);
      });

      test('has valid structure', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });

        const htmlLang = await p.getAttribute('html', 'lang');
        expect(htmlLang).toBeTruthy();

        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });
    });
  }
});

/**
 * SECTION 3: Component & Widget Tests
 */
test.describe('Admin Components & Widgets', () => {
  test('phase-tracker component loads', async ({ page }) => {
    const response = await page.goto('/admin/components/phase-tracker.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);

    const content = await page.content();
    expect(content).toContain('phase');
  });

  test('kpi-card widget loads', async ({ page }) => {
    const response = await page.goto('/admin/widgets/kpi-card.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);

    const content = await page.content();
    expect(content).toContain('kpi');
  });

  test('widgets-demo page renders all widgets', async ({ page }) => {
    const response = await page.goto('/admin/widgets-demo.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });
});

/**
 * SECTION 4: Landing Page Tests
 */
test.describe('Landing Page (lp.html)', () => {
  test('loads successfully', async ({ page }) => {
    const response = await page.goto('/lp.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has SEO meta tags', async ({ page }) => {
    await page.goto('/lp.html', { waitUntil: 'domcontentloaded' });

    const title = await page.title();
    expect(title.length).toBeGreaterThan(5);

    const description = await page.getAttribute('meta[name="description"]', 'content');
    expect(description).toBeTruthy();
    expect(description!.length).toBeGreaterThan(10);

    const viewport = await page.getAttribute('meta[name="viewport"]', 'content');
    expect(viewport).toBeTruthy();
  });

  test('has proper heading structure', async ({ page }) => {
    await page.goto('/lp.html', { waitUntil: 'domcontentloaded' });

    const h1Count = await page.locator('h1').count();
    expect(h1Count).toBeLessThanOrEqual(1);

    const h1Text = await page.textContent('h1');
    expect(h1Text?.length).toBeGreaterThan(0);
  });

  test('is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    const response = await page.goto('/lp.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);
  });
});

/**
 * SECTION 5: Auth Pages Tests
 */
test.describe('Auth Pages', () => {
  const AUTH_PAGES = [
    { path: '/auth/login.html', name: 'Auth Login' },
  ];

  for (const authPage of AUTH_PAGES) {
    test(`${authPage.name} loads`, async ({ page }) => {
      const response = await page.goto(authPage.path, {
        waitUntil: 'domcontentloaded',
        timeout: 10000
      });
      expect(response?.status()).toBe(200);
    });

    test(`${authPage.name} has login form`, async ({ page }) => {
      await page.goto(authPage.path, { waitUntil: 'domcontentloaded' });

      const hasEmailInput = await page.locator('input[type="email"], input[name="email"]').count();
      const hasPasswordInput = await page.locator('input[type="password"], input[name="password"]').count();
      const hasSubmitButton = await page.locator('button[type="submit"], input[type="submit"]').count();

      expect(hasEmailInput + hasPasswordInput + hasSubmitButton).toBeGreaterThan(0);
    });
  }
});

/**
 * SECTION 6: Affiliate Pages Tests
 */
test.describe('Affiliate Pages', () => {
  const AFFILIATE_PAGES = [
    { path: '/affiliate/dashboard.html', name: 'Affiliate Dashboard' },
    { path: '/affiliate/commissions.html', name: 'Affiliate Commissions' },
    { path: '/affiliate/links.html', name: 'Affiliate Links' },
    { path: '/affiliate/media.html', name: 'Affiliate Media' },
    { path: '/affiliate/profile.html', name: 'Affiliate Profile' },
    { path: '/affiliate/referrals.html', name: 'Affiliate Referrals' },
    { path: '/affiliate/settings.html', name: 'Affiliate Settings' },
  ];

  for (const page of AFFILIATE_PAGES) {
    test(`${page.name} loads`, async ({ page: p }) => {
      const errors: string[] = [];
      p.on('pageerror', (error) => {
        if (error.message.includes('supabase')) return;
        errors.push(error.message);
      });

      const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 10000 });
      expect(response?.status()).toBe(200);
    });
  }
});

/**
 * SECTION 7: Link Validation - Comprehensive Check
 */
test.describe('Link Validation - All Pages', () => {
  const PAGES_TO_CHECK = [
    '/admin/dashboard.html',
    '/admin/agents.html',
    '/admin/campaigns.html',
    '/portal/dashboard.html',
    '/affiliate/dashboard.html',
  ];

  for (const pagePath of PAGES_TO_CHECK) {
    test(`no broken links on ${pagePath}`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded' });

      const links = await page.locator('a[href]').all();
      const brokenLinks: string[] = [];

      for (const link of links.slice(0, 20)) { // Check first 20 links
        const href = await link.getAttribute('href');
        if (href && !href.startsWith('#') && !href.startsWith('javascript:') && !href.startsWith('mailto:')) {
          // Internal links only
          if (href.startsWith('/') || !href.includes('://')) {
            try {
              const response = await page.request.get(href);
              if (response.status() >= 400) {
                brokenLinks.push(`${href} -> ${response.status()}`);
              }
            } catch {
              // Ignore network errors
            }
          }
        }
      }

      expect(brokenLinks.length, `Broken links: ${brokenLinks.join(', ')}`).toBeLessThanOrEqual(3);
    });
  }
});

/**
 * SECTION 8: Performance - Page Load Time
 */
test.describe('Performance - Page Load Time', () => {
  const KEY_PAGES = [
    '/admin/dashboard.html',
    '/portal/dashboard.html',
    '/index.html',
  ];

  for (const pagePath of KEY_PAGES) {
    test(`${pagePath} loads within performance budget`, async ({ page }) => {
      const startTime = Date.now();
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded' });
      const loadTime = Date.now() - startTime;

      expect(response?.status()).toBe(200);
      expect(loadTime).toBeLessThan(5000); // 5 second budget
    });
  }
});
