import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — CSS FILES VALIDATION TEST
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 *
 * Coverage: Tests for all CSS files in assets/css/
 * Validates:
 * - File existence and size
 * - Valid CSS syntax
 * - Required selectors present
 * - Dark mode support
 * - Responsive breakpoints
 *
 * Total: 15+ CSS files tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

const CSS_FILES = [
  { path: '/assets/css/m3-agency.css', name: 'M3 Agency Design System', minSize: 10000 },
  { path: '/assets/css/agency-2026.css', name: 'Agency 2026 Styles', minSize: 5000 },
  { path: '/assets/css/admin-unified.css', name: 'Admin Unified Styles', minSize: 5000 },
  { path: '/assets/css/ui-animations.css', name: 'UI Animations', minSize: 3000 },
  { path: '/assets/css/lazy-loading.css', name: 'Lazy Loading', minSize: 1000 },
  { path: '/assets/css/responsive-enhancements.css', name: 'Responsive Enhancements', minSize: 2000 },
  { path: '/assets/css/responsive-fix-2026.css', name: 'Responsive Fix 2026', minSize: 2000 },
  { path: '/assets/css/responsive-table-layout.css', name: 'Responsive Table Layout', minSize: 1000 },
  { path: '/assets/css/hover-effects.css', name: 'Hover Effects Library', minSize: 10000 },
  { path: '/assets/css/widgets.css', name: 'Widgets Styles', minSize: 5000 },
  { path: '/assets/css/components.css', name: 'Components Styles', minSize: 3000 },
  { path: '/assets/css/dashboard.css', name: 'Dashboard Styles', minSize: 3000 },
  { path: '/assets/css/forms.css', name: 'Forms Styles', minSize: 2000 },
  { path: '/assets/css/navigation.css', name: 'Navigation Styles', minSize: 2000 },
  { path: '/assets/css/utilities.css', name: 'Utility Classes', minSize: 1000 },
];

test.describe('CSS Files Validation', () => {
  for (const css of CSS_FILES) {
    test.describe(`${css.name} (${css.path})`, () => {
      test('file exists and has valid CSS', async ({ page: p }) => {
        const response = await p.goto(css.path, { waitUntil: 'commit', timeout: 10000 });

        // HTTP 200
        expect(response?.status()).toBe(200);

        // Check CSS content
        const content = await response.text();

        // File size check
        expect(content.length).toBeGreaterThanOrEqual(css.minSize);

        // Valid CSS syntax checks
        expect(content).toContain('{');
        expect(content).toContain('}');

        // Should have selectors
        const selectorCount = (content.match(/[.#a-zA-Z][\w-]*\s*\{/g) || []).length;
        expect(selectorCount).toBeGreaterThan(5);
      });
    });
  }

  /**
   * Specific CSS Feature Tests
   */
  test.describe('Hover Effects Library', () => {
    test('should have button hover effects', async ({ page: p }) => {
      const response = await p.goto('/assets/css/hover-effects.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('.btn-hover-glow');
      expect(content).toContain('.btn-hover-scale');
      expect(content).toContain('.btn-hover-ripple');
    });

    test('should have card hover effects', async ({ page: p }) => {
      const response = await p.goto('/assets/css/hover-effects.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('.card-hover-lift');
      expect(content).toContain('.card-hover-glow');
      expect(content).toContain('.card-hover-scale');
    });

    test('should have dark mode support', async ({ page: p }) => {
      const response = await p.goto('/assets/css/hover-effects.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('[data-theme="dark"]');
    });

    test('should have mobile hover detection', async ({ page: p }) => {
      const response = await p.goto('/assets/css/hover-effects.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('@media (hover: none)');
    });
  });

  test.describe('Responsive CSS', () => {
    test('responsive-enhancements should have mobile breakpoints', async ({ page: p }) => {
      const response = await p.goto('/assets/css/responsive-enhancements.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toMatch(/@media.*max-width.*768px/);
    });

    test('responsive-fix-2026 should have tablet breakpoints', async ({ page: p }) => {
      const response = await p.goto('/assets/css/responsive-fix-2026.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toMatch(/@media.*max-width.*1024px/);
    });

    test('responsive-table-layout should handle small screens', async ({ page: p }) => {
      const response = await p.goto('/assets/css/responsive-table-layout.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toMatch(/@media.*max-width.*768px/);
      expect(content).toContain('table');
    });
  });

  test.describe('M3 Design System', () => {
    test('should have CSS custom properties', async ({ page: p }) => {
      const response = await p.goto('/assets/css/m3-agency.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('--md-sys-color');
      expect(content).toContain('--md-sys-type');
    });

    test('should have color tokens', async ({ page: p }) => {
      const response = await p.goto('/assets/css/m3-agency.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('--md-sys-color-primary');
      expect(content).toContain('--md-sys-color-secondary');
    });

    test('should have typography scale', async ({ page: p }) => {
      const response = await p.goto('/assets/css/m3-agency.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('--md-sys-type-display')
        || expect(content).toContain('--md-sys-type-headline')
        || expect(content).toContain('--md-sys-type-body');
    });
  });

  test.describe('Widgets CSS', () => {
    test('should have widget styles', async ({ page: p }) => {
      const response = await p.goto('/assets/css/widgets.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('.widget')
        || expect(content).toContain('.kpi')
        || expect(content).toContain('.chart');
    });
  });

  test.describe('UI Animations', () => {
    test('should have animation keyframes', async ({ page: p }) => {
      const response = await p.goto('/assets/css/ui-animations.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toContain('@keyframes');
    });

    test('should have transition utilities', async ({ page: p }) => {
      const response = await p.goto('/assets/css/ui-animations.css', { waitUntil: 'commit' });
      const content = await response.text();

      expect(content).toMatch(/transition[-\w]*:/);
    });
  });
});
