import { test, expect } from '@playwright/test';

/**
 * Dashboard Widgets E2E Tests
 * Tests for KPI cards, charts, alerts widgets
 *
 * Generated by: /frontend-ui-build
 * Date: 2026-03-13
 */

test.describe('Dashboard Widgets - Basic Rendering', () => {
  test('should render dashboard page', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await expect(page.locator('body')).toBeVisible();

    // Check page title
    const title = await page.title();
    expect(title).toMatch(/Admin|Dashboard/i);
  });

  test('should load widgets.css stylesheet', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const stylesheet = page.locator('link[rel="stylesheet"][href*="widgets.css"]');
    await expect(stylesheet).toHaveCount(1);
  });

  test('should load widget scripts', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(500);

    // Check if custom elements are defined
    const hasAlertsWidget = await page.evaluate(() => {
      return typeof customElements.get('alerts-widget') !== 'undefined';
    });

    expect(hasAlertsWidget).toBeTruthy();
  });
});

test.describe('KPI Card Widget', () => {
  test('should render KPI card with basic info', async ({ page }) => {
    await page.goto('/admin/widgets/kpi-card.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    // Should have a title - check for any heading or title element
    const hasTitle = await page.locator('h1, h2, h3, h4, h5, h6, [class*="title"], title').count() > 0;
    expect(hasTitle).toBeTruthy();

    // Should have content in body
    await expect(page.locator('body')).toBeVisible();
  });

  test('should have responsive layout', async ({ browser }) => {
    // Mobile viewport
    const mobileContext = await browser.newContext({ viewport: { width: 375, height: 667 } });
    const mobilePage = await mobileContext.newPage();
    await mobilePage.goto('/admin/widgets/kpi-card.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await expect(mobilePage.locator('body')).toBeVisible();
    await mobileContext.close();

    // Desktop viewport
    const desktopContext = await browser.newContext({ viewport: { width: 1440, height: 900 } });
    const desktopPage = await desktopContext.newPage();
    await desktopPage.goto('/admin/widgets/kpi-card.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await expect(desktopPage.locator('body')).toBeVisible();
    await desktopContext.close();
  }, { timeout: 60000 });
});

test.describe('Alerts Widget', () => {
  test('should initialize alerts-widget custom element', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(500);

    // Custom element should be registered
    const isRegistered = await page.evaluate(() => {
      return typeof customElements.get('alerts-widget') === 'function';
    });

    expect(isRegistered).toBeTruthy();
  });

  test('should render alerts-widget when present in DOM', async ({ page }) => {
    await page.goto('/admin/widgets-demo.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    // Widget should be visible or at least present
    const widget = page.locator('alerts-widget').first();
    const count = await widget.count();

    // If widget exists in demo page, it should be visible
    if (count > 0) {
      await expect(widget).toBeVisible();
    }
  });
});

test.describe('Chart Widgets', () => {
  test('should register pie-chart-widget custom element', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(500);

    const isRegistered = await page.evaluate(() => {
      return typeof customElements.get('pie-chart-widget') === 'function';
    });
    expect(isRegistered).toBeTruthy();
  });

  test('should register line-chart-widget custom element', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(500);

    const isRegistered = await page.evaluate(() => {
      return typeof customElements.get('line-chart-widget') === 'function';
    });
    expect(isRegistered).toBeTruthy();
  });

  test('should register bar-chart-widget custom element', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(500);

    const isRegistered = await page.evaluate(() => {
      return typeof customElements.get('bar-chart-widget') === 'function';
    });
    expect(isRegistered).toBeTruthy();
  });

  test('should register area-chart-widget custom element', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(500);

    const isRegistered = await page.evaluate(() => {
      return typeof customElements.get('area-chart-widget') === 'function';
    });
    expect(isRegistered).toBeTruthy();
  });
});

test.describe('Widget Accessibility', () => {
  test('should have lang attribute on html', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const lang = await page.getAttribute('html', 'lang');
    expect(lang).toBeTruthy();
  });

  test('should have main landmark', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const main = page.locator('main, [role="main"]');
    await expect(main).toBeVisible();
  });

  test('should have proper heading structure', async ({ page }) => {
    await page.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const h1 = page.locator('h1');
    await expect(h1).toHaveCount(1);
  });
});

test.describe('Widget Demo Page', () => {
  test('should load demo page successfully', async ({ page }) => {
    const response = await page.goto('/admin/widgets-demo.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    expect(response?.status()).toBe(200);
    await expect(page.locator('body')).toBeVisible();
  });

  test('should have all widget CSS loaded', async ({ page }) => {
    await page.goto('/admin/widgets-demo.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const widgetsCss = page.locator('link[rel="stylesheet"][href*="widgets.css"]');
    await expect(widgetsCss).toHaveCount(1);
  });
});
