import { test, expect } from '@playwright/test';

test.use({ viewport: { width: 1920, height: 1080 } });

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * F&B CONTAINER PAGES — SMOKE TEST SUITE
 *
 * Generated by: /dev:bug-sprint
 * Date: 2026-03-14
 *
 * Covers 7 F&B Container pages
 * ═══════════════════════════════════════════════════════════════════════════
 */

const FNB_PAGES = [
  { path: '/admin/pos.html', name: 'Admin POS' },
  { path: '/admin/menu.html', name: 'Admin Menu' },
  { path: '/admin/inventory.html', name: 'Admin Inventory' },
  { path: '/admin/shifts.html', name: 'Admin Shifts' },
  { path: '/admin/quality.html', name: 'Admin Quality (ATTP)' },
  { path: '/admin/suppliers.html', name: 'Admin Suppliers' },
  { path: '/admin/loyalty.html', name: 'Admin Loyalty' },
];

test.describe('F&B Container Pages — Smoke Tests', () => {
  for (const page of FNB_PAGES) {
    test(`${page.name} loads successfully`, async ({ page: p }) => {
      const errors: string[] = [];

      // Capture JS errors
      p.on('pageerror', (error) => {
        if (error.message.includes('supabase') || error.message.includes('Auth')) return;
        if (error.message.includes('__ENV__')) return;
        if (error.message.includes('CustomElementRegistry')) return;
        if (/is not defined/.test(error.message)) return;
        errors.push(error.message);
      });

      const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 15000 });

      expect(response?.status()).toBe(200);

      const title = await p.title();
      expect(title.length).toBeGreaterThan(0);

      expect(errors, `JS errors on ${page.path}: ${errors.join(', ')}`).toHaveLength(0);
    });
  }
});

/**
 * Functional Tests — F&B POS Page
 */
test.describe('F&B POS — Functional Tests', () => {
  test('POS page has content', async ({ page }) => {
    await page.goto('/admin/pos.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});

/**
 * Functional Tests — F&B Menu Page
 */
test.describe('F&B Menu — Functional Tests', () => {
  test('Menu page has content', async ({ page }) => {
    await page.goto('/admin/menu.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});

/**
 * Functional Tests — F&B Inventory Page
 */
test.describe('F&B Inventory — Functional Tests', () => {
  test('Inventory page has content', async ({ page }) => {
    await page.goto('/admin/inventory.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});

/**
 * Functional Tests — F&B Shifts Page
 */
test.describe('F&B Shifts — Functional Tests', () => {
  test('Shifts page has content', async ({ page }) => {
    await page.goto('/admin/shifts.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});

/**
 * Functional Tests — F&B Quality Page
 */
test.describe('F&B Quality — Functional Tests', () => {
  test('Quality page has content', async ({ page }) => {
    await page.goto('/admin/quality.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});

/**
 * Functional Tests — F&B Suppliers Page
 */
test.describe('F&B Suppliers — Functional Tests', () => {
  test('Suppliers page has content', async ({ page }) => {
    await page.goto('/admin/suppliers.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});

/**
 * Functional Tests — F&B Loyalty Page
 */
test.describe('F&B Loyalty — Functional Tests', () => {
  test('Loyalty page has content', async ({ page }) => {
    await page.goto('/admin/loyalty.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    const content = await page.content();
    expect(content.length).toBeGreaterThan(100);
  });
});
