import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — JAVASCRIPT UTILITIES TEST
 *
 * Generated by: /dev-bug-script
 * Date: 2026-03-13
 *
 * Coverage: Tests for all JS utility files in assets/js/
 * - core-utils.js
 * - enhanced-utils.js
 * - format-utils.js (shared)
 * - api-utils.js (shared)
 * - dom-utils.js (shared)
 * - admin-shared.js
 * - admin-guard.js
 * - form-validation.js
 *
 * Total: 8 utility modules tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

test.describe('JavaScript Utilities — Unit Tests', () => {
  /**
   * Core Utils Tests
   */
  test.describe('Core Utils (core-utils.js)', () => {
    test('should export formatCurrency function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasFormatCurrency = await p.evaluate(() => {
        return typeof window.formatCurrency === 'function';
      });

      expect(hasFormatCurrency).toBe(true);
    });

    test('formatCurrency should format numbers correctly', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return window.formatCurrency(1234567.89);
      });

      expect(result).toMatch(/1\.234\.567/);
    });

    test('should export formatNumber function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasFormatNumber = await p.evaluate(() => {
        return typeof window.formatNumber === 'function';
      });

      expect(hasFormatNumber).toBe(true);
    });

    test('should export formatDate function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasFormatDate = await p.evaluate(() => {
        return typeof window.formatDate === 'function';
      });

      expect(hasFormatDate).toBe(true);
    });

    test('formatDate should format dates', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return window.formatDate(new Date('2026-03-13'));
      });

      expect(result.length).toBeGreaterThan(0);
    });

    test('should export slugify function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasSlugify = await p.evaluate(() => {
        return typeof window.slugify === 'function';
      });

      expect(hasSlugify).toBe(true);
    });

    test('slugify should convert text to slug', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return window.slugify('Hello World! This is a Test');
      });

      expect(result).toBe('hello-world-this-is-a-test');
    });

    test('should export debounce function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasDebounce = await p.evaluate(() => {
        return typeof window.debounce === 'function';
      });

      expect(hasDebounce).toBe(true);
    });

    test('should export throttle function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasThrottle = await p.evaluate(() => {
        return typeof window.throttle === 'function';
      });

      expect(hasThrottle).toBe(true);
    });

    test('should export parseQuery function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasParseQuery = await p.evaluate(() => {
        return typeof window.parseQuery === 'function';
      });

      expect(hasParseQuery).toBe(true);
    });
  });

  /**
   * Enhanced Utils Tests
   */
  test.describe('Enhanced Utils (enhanced-utils.js)', () => {
    test('should export toCurrency function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasToCurrency = await p.evaluate(() => {
        return typeof window.toCurrency === 'function';
      });

      expect(hasToCurrency).toBe(true);
    });

    test('toCurrency should match formatCurrency', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        const val = 1000000;
        return {
          formatCurrency: window.formatCurrency(val),
          toCurrency: window.toCurrency(val)
        };
      });

      // Both should produce similar output
      expect(result.formatCurrency).toEqual(result.toCurrency);
    });

    test('should export truncate function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasTruncate = await p.evaluate(() => {
        return typeof window.truncate === 'function';
      });

      expect(hasTruncate).toBe(true);
    });

    test('truncate should limit text length', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return window.truncate('Hello World This Is A Long Text', 10);
      });

      expect(result.length).toBeLessThanOrEqual(13); // 10 + '...'
    });

    test('should export isEmpty function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasIsEmpty = await p.evaluate(() => {
        return typeof window.isEmpty === 'function';
      });

      expect(hasIsEmpty).toBe(true);
    });

    test('isEmpty should detect empty values', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return {
          nullVal: window.isEmpty(null),
          emptyStr: window.isEmpty(''),
          emptyArr: window.isEmpty([]),
          emptyObj: window.isEmpty({}),
          nonEmpty: window.isEmpty('hello')
        };
      });

      expect(result.nullVal).toBe(true);
      expect(result.emptyStr).toBe(true);
      expect(result.emptyArr).toBe(true);
      expect(result.emptyObj).toBe(true);
      expect(result.nonEmpty).toBe(false);
    });

    test('should export isEmail function', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const hasIsEmail = await p.evaluate(() => {
        return typeof window.isEmail === 'function';
      });

      expect(hasIsEmail).toBe(true);
    });

    test('isEmail should validate emails', async ({ page: p }) => {
      await p.goto('/', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return {
          valid: window.isEmail('test@example.com'),
          invalid: window.isEmail('not-an-email')
        };
      });

      expect(result.valid).toBe(true);
      expect(result.invalid).toBe(false);
    });
  });

  /**
   * Form Validation Tests
   */
  test.describe('Form Validation (form-validation.js)', () => {
    test('should export validateRequired function', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const hasValidateRequired = await p.evaluate(() => {
        return typeof window.validateRequired === 'function';
      });

      expect(hasValidateRequired).toBe(true);
    });

    test('validateRequired should validate fields', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return {
          empty: window.validateRequired(''),
          whitespace: window.validateRequired('   '),
          filled: window.validateRequired('hello')
        };
      });

      expect(result.empty).toBe(false);
      expect(result.whitespace).toBe(false);
      expect(result.filled).toBe(true);
    });

    test('should export validateEmail function', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const hasValidateEmail = await p.evaluate(() => {
        return typeof window.validateEmail === 'function';
      });

      expect(hasValidateEmail).toBe(true);
    });

    test('should export validatePhone function', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const hasValidatePhone = await p.evaluate(() => {
        return typeof window.validatePhone === 'function';
      });

      expect(hasValidatePhone).toBe(true);
    });

    test('should export validatePassword function', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const hasValidatePassword = await p.evaluate(() => {
        return typeof window.validatePassword === 'function';
      });

      expect(hasValidatePassword).toBe(true);
    });

    test('validatePassword should check minimum length', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const result = await p.evaluate(() => {
        return {
          short: window.validatePassword('123'),
          min: window.validatePassword('123456'),
          long: window.validatePassword('123456789')
        };
      });

      expect(result.short).toBe(false);
      expect(result.min).toBe(true);
      expect(result.long).toBe(true);
    });
  });

  /**
   * Admin Guard Tests
   */
  test.describe('Admin Guard (admin-guard.js)', () => {
    test('should export isAdminLoggedIn function', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const hasIsAdminLoggedIn = await p.evaluate(() => {
        return typeof window.isAdminLoggedIn === 'function';
      });

      expect(hasIsAdminLoggedIn).toBe(true);
    });

    test('should export requireAuth function', async ({ page: p }) => {
      await p.goto('/admin/auth.html', { waitUntil: 'domcontentloaded' });

      const hasRequireAuth = await p.evaluate(() => {
        return typeof window.requireAuth === 'function';
      });

      expect(hasRequireAuth).toBe(true);
    });
  });

  /**
   * Admin Shared Tests
   */
  test.describe('Admin Shared (admin-shared.js)', () => {
    test('should initialize admin UI', async ({ page: p }) => {
      await p.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

      // Check if admin shared functions are available
      const hasAdminFunctions = await p.evaluate(() => {
        return typeof window.initAdminUI === 'function' ||
               typeof window.setupAdminNav === 'function' ||
               typeof window.handleAdminSidebar === 'function';
      });

      // At least one admin function should exist
      expect(hasAdminFunctions).toBe(true);
    });
  });
});

/**
 * Integration Tests — Utilities Working Together
 */
test.describe('Integration Tests — Utilities', () => {
  test('should format currency in UI elements', async ({ page: p }) => {
    await p.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

    // Check if KPI cards have formatted numbers
    const kpiValues = await p.evaluate(() => {
      const kpiElements = document.querySelectorAll('.kpi-value, .kpi-card .value');
      return Array.from(kpiElements).map(el => el.textContent.trim());
    });

    // At least some KPI values should exist
    expect(kpiValues.length).toBeGreaterThan(0);
  });

  test('should have working theme toggle', async ({ page: p }) => {
    await p.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

    // Check if Theme object exists
    const hasTheme = await p.evaluate(() => {
      return typeof window.Theme !== 'undefined';
    });

    expect(hasTheme).toBe(true);
  });

  test('should have working loading states', async ({ page: p }) => {
    await p.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

    // Check if Loading object exists
    const hasLoading = await p.evaluate(() => {
      return typeof window.Loading !== 'undefined';
    });

    expect(hasLoading).toBe(true);
  });

  test('should have working micro animations', async ({ page: p }) => {
    await p.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

    // Check if MicroAnimations object exists
    const hasMicroAnimations = await p.evaluate(() => {
      return typeof window.MicroAnimations !== 'undefined';
    });

    expect(hasMicroAnimations).toBe(true);
  });

  test('should have working toast notifications', async ({ page: p }) => {
    await p.goto('/admin/dashboard.html', { waitUntil: 'domcontentloaded' });

    // Check if Toast object exists
    const hasToast = await p.evaluate(() => {
      return typeof window.Toast !== 'undefined';
    });

    expect(hasToast).toBe(true);
  });
});
