import { test, expect } from '@playwright/test';

/**
 * Portal Subscription Plans Tests
 * Tests for /portal/subscription-plans.html
 *
 * Generated by: /dev-bug-sprint "Viet tests cover untested pages"
 * Date: 2026-03-13
 */

test.describe('Subscription Plans - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
      errors.push(error.message);
    });

    const response = await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });

  test('should have valid HTML structure', async ({ page }) => {
    await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const hasDoctype = await page.evaluate(() => document.doctype?.name === 'html');
    expect(hasDoctype).toBeTruthy();
  });

  test('should have required meta tags', async ({ page }) => {
    await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const title = await page.title();
    expect(title.length).toBeGreaterThan(5);

    const description = await page.getAttribute('meta[name="description"]', 'content');
    expect(description?.length).toBeGreaterThan(10);

    const viewport = await page.getAttribute('meta[name="viewport"]', 'content');
    expect(viewport).toBeTruthy();
  });
});

test.describe('Subscription Plans - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display pricing cards', async ({ page }) => {
    const mainContent = page.locator('main, [role="main"]');
    await expect(mainContent).toBeVisible();

    // Pricing cards should exist
    const pricingCards = page.locator('[class*="pricing"], [class*="plan"], [class*="tier"]');
    const count = await pricingCards.count();

    // Should have at least 2 pricing tiers
    expect(count).toBeGreaterThanOrEqual(2);
  });

  test('should have plan features list', async ({ page }) => {
    const featureLists = page.locator('[class*="feature"], ul li');
    const count = await featureLists.count();

    // Should have feature items
    expect(count).toBeGreaterThanOrEqual(5);
  });

  test('should have subscribe/select buttons', async ({ page }) => {
    const actionButtons = page.locator('button, [class*="btn"], [class*="subscribe"]');
    const count = await actionButtons.count();

    // Should have action buttons
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('pricing cards have proper structure', async ({ page }) => {
    const pricingCard = page.locator('[class*="pricing"], [class*="plan"], [class*="tier"]').first();
    await expect(pricingCard).toBeVisible();

    // Card should have price
    const priceEl = pricingCard.locator('[class*="price"], [class*="amount"]');
    const isVisible = await priceEl.isVisible();
    expect(isVisible).toBeTruthy();
  });
});

test.describe('Subscription Plans - Responsive', () => {
  const viewports = [
    { name: 'mobile', width: 375, height: 667 },
    { name: 'tablet', width: 768, height: 1024 },
    { name: 'desktop', width: 1440, height: 900 },
  ];

  for (const vp of viewports) {
    test(`should render correctly on ${vp.name} (${vp.width}x${vp.height})`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height });
      await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

      const mainContent = page.locator('main, [role="main"]');
      await expect(mainContent).toBeVisible();
    });
  }
});

test.describe('Subscription Plans - Interactions', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/subscription-plans.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(1500);
  });

  test('should toggle monthly/yearly pricing if available', async ({ page }) => {
    const toggle = page.locator('[class*="toggle"], [class*="switch"], [class*="billing-type"]');
    const isVisible = await toggle.isVisible();

    if (isVisible) {
      await expect(toggle).toBeEnabled();
      await toggle.click();
      await page.waitForTimeout(500);

      // Prices should update
      const prices = page.locator('[class*="price"], [class*="amount"]');
      const count = await prices.count();
      expect(count).toBeGreaterThan(0);
    }
  });
});
