import { test, expect } from '@playwright/test';

/**
 * Portal Core Pages - Functional Tests
 * Covers: login, approve, payment-result, assets, credits
 * 
 * Generated by: /dev:bug-sprint
 * Date: 2026-03-13
 */

test.describe('Portal Login Page', () => {
  test('login.html loads with all form elements', async ({ page }) => {
    await page.goto('/portal/login.html', { waitUntil: 'domcontentloaded' });
    
    // Has email input
    const emailInput = page.locator('input[type="email"], input[name="email"]');
    await expect(emailInput).toBeVisible();
    
    // Has password input
    const passwordInput = page.locator('input[type="password"]');
    await expect(passwordInput).toBeVisible();
    
    // Has submit button
    const submitBtn = page.locator('button[type="submit"], input[type="submit"]');
    await expect(submitBtn).toBeVisible();
    
    // Has forgot password link
    const forgotLink = page.locator('a:has-text("Quên"), a:has-text("forgot"), a[href*="forgot"]');
    await expect(forgotLink).toBeVisible();
  });
});

test.describe('Portal Approve Page', () => {
  test('approve.html loads correctly', async ({ page }) => {
    await page.goto('/portal/approve.html', { waitUntil: 'domcontentloaded' });
    
    // Should have approval-related content
    const content = await page.content();
    expect(content).toMatch(/duyệt|approve|approval|confirm/i);
  });
});

test.describe('Portal Payment Result Page', () => {
  test('payment-result.html displays result', async ({ page }) => {
    await page.goto('/portal/payment-result.html', { waitUntil: 'domcontentloaded' });
    
    // Should have payment result elements
    const content = await page.content();
    expect(content).toMatch(/thành công|thất bại|success|failed|payment|result/i);
  });
});

test.describe('Portal Assets Page', () => {
  test('assets.html loads with asset management', async ({ page }) => {
    await page.goto('/portal/assets.html', { waitUntil: 'domcontentloaded' });
    
    // Should have asset-related content
    const content = await page.content();
    expect(content).toMatch(/asset|content|media|library|upload/i);
  });
});

test.describe('Portal Credits Page', () => {
  test('credits.html displays credit balance', async ({ page }) => {
    await page.goto('/portal/credits.html', { waitUntil: 'domcontentloaded' });
    
    // Should have credits-related content
    const content = await page.content();
    expect(content).toMatch(/credit|balance|nạp|purchase|package/i);
  });
});

test.describe('Portal Onboarding Page', () => {
  test('onboarding.html has step navigation', async ({ page }) => {
    await page.goto('/portal/onboarding.html', { waitUntil: 'domcontentloaded' });
    
    // Should have onboarding steps
    const content = await page.content();
    expect(content).toMatch(/step|bước|welcome|onboard/i);
    
    // Should have navigation buttons
    const nextBtns = page.locator('[onclick*="next"], [onclick*="Step"], button:has-text("Tiếp"), button:has-text("Next")');
    await expect(nextBtns.first()).toBeVisible();
  });
});

test.describe('Portal Projects Page', () => {
  test('projects.html displays project list', async ({ page }) => {
    await page.goto('/portal/projects.html', { waitUntil: 'domcontentloaded' });
    
    // Should have project-related content
    const content = await page.content();
    expect(content).toMatch(/project|dự án|campaign|chiến dịch/i);
  });
});

test.describe('Portal Invoices Page', () => {
  test('invoices.html displays invoice list', async ({ page }) => {
    await page.goto('/portal/invoices.html', { waitUntil: 'domcontentloaded' });
    
    // Should have invoice-related content
    const content = await page.content();
    expect(content).toMatch(/invoice|hóa đơn|billing|payment/i);
    
    // Should have table structure
    const table = page.locator('table, .invoice-table, [role="table"]');
    await expect(table.first()).toBeVisible();
  });
});

test.describe('Portal Reports Page', () => {
  test('reports.html displays analytics reports', async ({ page }) => {
    await page.goto('/portal/reports.html', { waitUntil: 'domcontentloaded' });
    
    // Should have report-related content
    const content = await page.content();
    expect(content).toMatch(/report|analytics|phân tích|thống kê/i);
  });
});

test.describe('Portal Subscriptions Page', () => {
  test('subscriptions.html displays subscription list', async ({ page }) => {
    await page.goto('/portal/subscriptions.html', { waitUntil: 'domcontentloaded' });
    
    // Should have subscription-related content
    const content = await page.content();
    expect(content).toMatch(/subscription|gói|plan|đăng ký/i);
  });
});
