import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — PORTAL PAGES COVERAGE TEST
 * Test coverage cho các portal pages chưa được test đầy đủ
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-14
 * Coverage Goal: 100% portal pages tested
 * ═══════════════════════════════════════════════════════════════════════════
 */

/**
 * PORTAL PAGES - Functional Tests
 * Test các portal pages với functional checks
 */
test.describe('Portal Pages - Functional Coverage', () => {
  const PORTAL_PAGES = [
    { path: '/portal/invoices.html', name: 'Invoices', expectedElements: ['invoice', 'bill', 'payment'] },
    { path: '/portal/payments.html', name: 'Payments', expectedElements: ['payment', 'transaction', 'amount'] },
    { path: '/portal/missions.html', name: 'Missions', expectedElements: ['mission', 'task', 'campaign'] },
    { path: '/portal/credits.html', name: 'Credits', expectedElements: ['credit', 'balance', 'MCU'] },
    { path: '/portal/assets.html', name: 'Assets', expectedElements: ['asset', 'file', 'upload'] },
    { path: '/portal/projects.html', name: 'Projects', expectedElements: ['project', 'progress', 'status'] },
    { path: '/portal/reports.html', name: 'Reports', expectedElements: ['report', 'analytics', 'metric'] },
    { path: '/portal/notifications.html', name: 'Notifications', expectedElements: ['notification', 'alert', 'message'] },
    { path: '/portal/ocop-catalog.html', name: 'OCOP Catalog', expectedElements: ['catalog', 'product', 'ocop'] },
    { path: '/portal/subscription-plans.html', name: 'Subscription Plans', expectedElements: ['subscription', 'plan', 'pricing'] },
    { path: '/portal/subscriptions.html', name: 'My Subscriptions', expectedElements: ['subscription', 'active', 'billing'] },
    { path: '/portal/roi-analytics.html', name: 'ROI Analytics', expectedElements: ['roi', 'analytics', 'conversion'] },
    { path: '/portal/roi-report.html', name: 'ROI Report', expectedElements: ['roi', 'report', 'revenue'] },
    { path: '/portal/roiaas-dashboard.html', name: 'ROIaaS Dashboard', expectedElements: ['dashboard', 'roi', 'analytics'] },
    { path: '/portal/roiaas-onboarding.html', name: 'ROIaaS Onboarding', expectedElements: ['onboarding', 'setup', 'guide'] },
  ];

  for (const page of PORTAL_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];
        p.on('pageerror', (error) => {
          // Ignore expected errors ( Supabase config, env vars not loaded in test)
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        // Allow up to 3 non-critical errors
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });

        // Check DOCTYPE
        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);

        // Check html lang
        const htmlLang = await p.getAttribute('html', 'lang');
        expect(htmlLang).toBeTruthy();

        // Check title
        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });

      test('has required meta tags', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });

        // Viewport
        const viewport = await p.getAttribute('meta[name="viewport"]', 'content');
        expect(viewport).toBeTruthy();

        // Charset
        const charset = await p.querySelector('meta[charset]');
        expect(charset).toBeTruthy();
      });

      test('has no broken internal images', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 30000 });

        const images = await p.locator('img[src]').all();
        const brokenImages: string[] = [];

        for (const img of images.slice(0, 10)) { // Check first 10 images
          const src = await img.getAttribute('src');
          if (src && !src.startsWith('http') && !src.startsWith('data:')) {
            const imgResponse = await p.goto(p.url() + '/../' + src, { waitUntil: 'commit', timeout: 5000 }).catch(() => null);
            if (imgResponse?.status() !== 200) {
              brokenImages.push(src);
            }
          }
        }

        // Allow up to 2 broken images (not critical for functionality)
        expect(brokenImages.length).toBeLessThanOrEqual(2);
      });
    });
  }
});

/**
 * PORTAL LOGIN - Specific Tests
 */
test.describe('Portal Login', () => {
  test('loads login page', async ({ page }) => {
    const response = await page.goto('/portal/login.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has login form', async ({ page }) => {
    await page.goto('/portal/login.html', { waitUntil: 'domcontentloaded' });

    const hasEmailInput = await page.locator('input[type="email"], input[name="email"]').count();
    const hasPasswordInput = await page.locator('input[type="password"], input[name="password"]').count();
    const hasSubmitButton = await page.locator('button[type="submit"], input[type="submit"]').count();

    expect(hasEmailInput + hasPasswordInput + hasSubmitButton).toBeGreaterThan(0);
  });

  test('has forgot password link', async ({ page }) => {
    await page.goto('/portal/login.html', { waitUntil: 'domcontentloaded' });

    const forgotPasswordLink = await page.locator('a[href*="forgot"], a:has-text("Forgot"), a:has-text("Quên mật khẩu")').count();
    // Not failing if missing, just logging
    if (forgotPasswordLink === 0) {
      console.log('Missing forgot password link on portal login');
    }
  });
});

/**
 * PAYMENT RESULT - Specific Tests
 */
test.describe('Payment Result Page', () => {
  test('loads payment result page', async ({ page }) => {
    const response = await page.goto('/portal/payment-result.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has payment status indicator', async ({ page }) => {
    await page.goto('/portal/payment-result.html', { waitUntil: 'domcontentloaded' });

    const hasStatusIndicator = await page.locator('[class*="status"], [class*="result"], [class*="success"], [class*="error"]').count();
    expect(hasStatusIndicator).toBeGreaterThan(0);
  });
});

/**
 * OCOP EXPORTER - Specific Tests
 */
test.describe('OCOP Exporter', () => {
  test('loads ocop exporter page', async ({ page }) => {
    const response = await page.goto('/portal/ocop-exporter.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has export functionality', async ({ page }) => {
    await page.goto('/portal/ocop-exporter.html', { waitUntil: 'domcontentloaded' });

    const hasExportButton = await page.locator('button:has-text("Export"), button:has-text("Xuất"), [class*="export"]').count();
    const hasExportOptions = await page.locator('select[name="format"], select[name="type"]').count();

    expect(hasExportButton + hasExportOptions).toBeGreaterThan(0);
  });
});

/**
 * ONBOARDING - Specific Tests
 */
test.describe('Onboarding Flow', () => {
  test('loads onboarding page', async ({ page }) => {
    const response = await page.goto('/portal/onboarding.html', {
      waitUntil: 'domcontentloaded',
      timeout: 10000
    });
    expect(response?.status()).toBe(200);
  });

  test('has step indicators', async ({ page }) => {
    await page.goto('/portal/onboarding.html', { waitUntil: 'domcontentloaded' });

    const stepIndicators = await page.locator('[class*="step"], [class*="progress"], [data-step]').count();
    expect(stepIndicators).toBeGreaterThan(0);
  });

  test('has navigation buttons', async ({ page }) => {
    await page.goto('/portal/onboarding.html', { waitUntil: 'domcontentloaded' });

    const nextButton = await page.locator('button:has-text("Tiếp"), button:has-text("Next"), .next, [class*="next"]').count();
    expect(nextButton).toBeGreaterThan(0);
  });
});

/**
 * ACCESSIBILITY - Quick Checks
 */
test.describe('Portal Accessibility', () => {
  const KEY_PAGES = [
    '/portal/dashboard.html',
    '/portal/invoices.html',
    '/portal/payments.html',
    '/portal/missions.html',
  ];

  for (const pagePath of KEY_PAGES) {
    test(`${pagePath} has accessible labels`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });

      // Check for role attributes
      const hasMainRole = await page.locator('[role="main"], main').count();
      const hasNavRole = await page.locator('[role="navigation"], nav').count();

      // At least one semantic element should exist
      expect(hasMainRole + hasNavRole).toBeGreaterThan(0);
    });

    test(`${pagePath} has sufficient color contrast`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });

      // Basic check: page should render without errors
      const bodyVisible = await page.locator('body').isVisible();
      expect(bodyVisible).toBe(true);
    });
  }
});

/**
 * RESPONSIVE - Mobile Viewport Tests
 */
test.describe('Portal Responsive', () => {
  test('portal dashboard is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 }); // iPhone 12 mini
    const response = await page.goto('/portal/dashboard.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);

    // Check viewport meta tag
    const viewport = await page.getAttribute('meta[name="viewport"]', 'content');
    expect(viewport).toContain('width=device-width');
  });

  test('portal invoices is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 768, height: 1024 }); // iPad
    const response = await page.goto('/portal/invoices.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);
  });

  test('portal payments is responsive', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 }); // iPhone 12/13 Pro
    const response = await page.goto('/portal/payments.html', { waitUntil: 'domcontentloaded' });
    expect(response?.status()).toBe(200);
  });
});
