import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — REMAINING PAGES COVERAGE TEST
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-14
 *
 * Coverage: Additional pages not covered by other test files
 * Focus: Demo pages, specialized features, F&B specific pages
 * ═══════════════════════════════════════════════════════════════════════════
 */

/**
 * DEMO & COMPONENTS PAGES
 */
test.describe('Demo & Components Pages', () => {
  const DEMO_PAGES = [
    { path: '/admin/components-demo.html', name: 'Components Demo', keywords: ['components', 'ui', 'demo'] },
    { path: '/admin/ui-components-demo.html', name: 'UI Components Demo', keywords: ['ui', 'components', 'material'] },
    { path: '/admin/ui-demo.html', name: 'UI Demo', keywords: ['ui', 'demo', 'interface'] },
    { path: '/admin/ux-components-demo.html', name: 'UX Components Demo', keywords: ['ux', 'components', 'experience'] },
    { path: '/admin/widgets-demo.html', name: 'Widgets Demo', keywords: ['widgets', 'demo', 'dashboard'] },
    { path: '/admin/features-demo.html', name: 'Features Demo', keywords: ['features', 'demo', 'showcase'] },
    { path: '/admin/features-demo-2027.html', name: 'Features Demo 2027', keywords: ['features', '2027', 'future'] },
  ];

  for (const page of DEMO_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (error.message.includes('CustomElementRegistry')) return;
          if (error.message.includes('hover') || error.message.includes('touch')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(5);
      });

      test('has valid title', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
        expect(title.toLowerCase()).toContain(page.keywords[0]);
      });
    });
  }
});

/**
 * F&B SPECIFIC PAGES
 */
test.describe('F&B Specific Pages', () => {
  const FB_PAGES = [
    { path: '/admin/menu.html', name: 'Menu Management', keywords: ['menu', 'food', 'beverage'] },
    { path: '/admin/pos.html', name: 'POS System', keywords: ['pos', 'point of sale', 'checkout'] },
    { path: '/admin/inventory.html', name: 'Inventory', keywords: ['inventory', 'stock', 'warehouse'] },
    { path: '/admin/suppliers.html', name: 'Suppliers', keywords: ['suppliers', 'vendor', 'procurement'] },
    { path: '/admin/quality.html', name: 'Quality Control', keywords: ['quality', 'control', 'assurance'] },
  ];

  for (const page of FB_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has main content area', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 30000 });

        const mainContent = await p.locator('main, [role="main"], .main-content, #main-content').count();
        expect(mainContent).toBeGreaterThan(0);
      });
    });
  }
});

/**
 * SPECIALIZED BUSINESS PAGES
 */
test.describe('Specialized Business Pages', () => {
  const BIZ_PAGES = [
    { path: '/admin/hr-hiring.html', name: 'HR & Hiring', keywords: ['hr', 'hiring', 'recruitment'] },
    { path: '/admin/lms.html', name: 'LMS', keywords: ['lms', 'learning', 'training'] },
    { path: '/admin/loyalty.html', name: 'Loyalty Program', keywords: ['loyalty', 'rewards', 'retention'] },
    { path: '/admin/pricing.html', name: 'Pricing', keywords: ['pricing', 'plans', 'subscription'] },
    { path: '/admin/proposals.html', name: 'Proposals', keywords: ['proposals', 'quotes', 'estimates'] },
    { path: '/admin/raas-overview.html', name: 'RaaS Overview', keywords: ['raas', 'overview', 'agency'] },
    { path: '/admin/vc-readiness.html', name: 'VC Readiness', keywords: ['vc', 'investor', 'funding'] },
    { path: '/admin/zalo.html', name: 'Zalo Integration', keywords: ['zalo', 'chat', 'messaging'] },
  ];

  for (const page of BIZ_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has viewport meta tag', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        const viewport = await p.getAttribute('meta[name="viewport"]', 'content');
        expect(viewport).toBeTruthy();
      });
    });
  }
});

/**
 * PORTAL ADDITIONAL PAGES
 */
test.describe('Portal Additional Pages', () => {
  const PORTAL_PAGES = [
    { path: '/portal/assets.html', name: 'Assets', keywords: ['assets', 'resources', 'media'] },
    { path: '/portal/notifications.html', name: 'Notifications', keywords: ['notifications', 'alerts', 'messages'] },
  ];

  for (const page of PORTAL_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has canonical URL', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        const canonical = await p.getAttribute('link[rel="canonical"]', 'href');
        expect(canonical).toBeTruthy();
      });
    });
  }
});

/**
 * AFFILIATE PAGES
 */
test.describe('Affiliate Pages', () => {
  const AFFILIATE_PAGES = [
    { path: '/affiliate/links.html', name: 'Affiliate Links', keywords: ['affiliate', 'links', 'referral'] },
    { path: '/affiliate/settings.html', name: 'Affiliate Settings', keywords: ['affiliate', 'settings', 'configuration'] },
  ];

  for (const page of AFFILIATE_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(3);
      });
    });
  }
});

/**
 * RESPONSIVE CHECK FOR ALL NEW PAGES
 */
test.describe('Responsive Check - New Pages', () => {
  const ALL_NEW_PAGES = [
    // Demo pages
    '/admin/components-demo.html',
    '/admin/ui-components-demo.html',
    '/admin/ui-demo.html',
    '/admin/ux-components-demo.html',
    '/admin/widgets-demo.html',
    '/admin/features-demo.html',
    '/admin/features-demo-2027.html',
    // F&B pages
    '/admin/menu.html',
    '/admin/pos.html',
    '/admin/inventory.html',
    '/admin/suppliers.html',
    '/admin/quality.html',
    // Business pages
    '/admin/hr-hiring.html',
    '/admin/lms.html',
    '/admin/loyalty.html',
    '/admin/pricing.html',
    '/admin/proposals.html',
    '/admin/raas-overview.html',
    '/admin/vc-readiness.html',
    '/admin/zalo.html',
    // Portal
    '/portal/assets.html',
    '/portal/notifications.html',
    // Affiliate
    '/affiliate/links.html',
    '/affiliate/settings.html',
  ];

  test('renders on mobile viewport (375px)', async ({ browser }) => {
    const context = await browser.newContext({
      viewport: { width: 375, height: 667 },
    });
    const page = await context.newPage();

    for (const path of ALL_NEW_PAGES) {
      await test.step(`Check ${path} on mobile`, async () => {
        const response = await page.goto(path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);

        // Check viewport meta
        const viewport = await page.getAttribute('meta[name="viewport"]', 'content');
        expect(viewport).toBeTruthy();
      });
    }

    await context.close();
  });

  test('renders on tablet viewport (768px)', async ({ browser }) => {
    const context = await browser.newContext({
      viewport: { width: 768, height: 1024 },
    });
    const page = await context.newPage();

    for (const path of ALL_NEW_PAGES) {
      await test.step(`Check ${path} on tablet`, async () => {
        const response = await page.goto(path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
      });
    }

    await context.close();
  });

  test('renders on desktop viewport (1024px)', async ({ browser }) => {
    const context = await browser.newContext({
      viewport: { width: 1024, height: 768 },
    });
    const page = await context.newPage();

    for (const path of ALL_NEW_PAGES) {
      await test.step(`Check ${path} on desktop`, async () => {
        const response = await page.goto(path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
      });
    }

    await context.close();
  });
});

/**
 * SEO VALIDATION FOR NEW PAGES
 */
test.describe('SEO Validation - New Pages', () => {
  const SEO_PAGES = [
    '/admin/menu.html',
    '/admin/pos.html',
    '/admin/inventory.html',
    '/admin/hr-hiring.html',
    '/admin/lms.html',
    '/admin/loyalty.html',
    '/portal/assets.html',
    '/portal/notifications.html',
  ];

  for (const path of SEO_PAGES) {
    test.describe(`${path}`, () => {
      test('has title tag', async ({ page: p }) => {
        await p.goto(path, { waitUntil: 'commit', timeout: 30000 });
        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });

      test('has meta description', async ({ page: p }) => {
        await p.goto(path, { waitUntil: 'commit', timeout: 30000 });
        const description = await p.getAttribute('meta[name="description"]', 'content');
        expect(description).toBeTruthy();
        expect(description.length).toBeGreaterThan(50);
      });

      test('has og:title tag', async ({ page: p }) => {
        await p.goto(path, { waitUntil: 'commit', timeout: 30000 });
        const ogTitle = await p.getAttribute('meta[property="og:title"]', 'content');
        expect(ogTitle).toBeTruthy();
      });
    });
  }
});
