import { test, expect } from '@playwright/test';

/**
 * ROIaaS Analytics Tests
 * Tests for roi-analytics.html page
 *
 * Generated by: /dev-bug-sprint "Viet tests cover untested pages"
 * Date: 2026-03-13
 */

test.describe('ROI Analytics - Page Load', () => {
  test('should load without critical errors', async ({ page }) => {
    const errors: string[] = [];

    page.on('pageerror', (error) => {
      if (error.message.includes('supabase')) return;
      if (error.message.includes('__ENV__')) return;
      if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
      errors.push(error.message);
    });

    const response = await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    expect(response?.status()).toBe(200);
    expect(errors).toHaveLength(0);
  });

  test('should have valid HTML structure', async ({ page }) => {
    await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const hasDoctype = await page.evaluate(() => document.doctype?.name === 'html');
    const hasHtml = await page.locator('html').count();
    const hasHead = await page.locator('head').count();
    const hasBody = await page.locator('body').count();

    expect(hasDoctype).toBeTruthy();
    expect(hasHead).toBe(1);
    expect(hasBody).toBe(1);
  });

  test('should have required meta tags', async ({ page }) => {
    await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const title = await page.title();
    expect(title.length).toBeGreaterThan(5);

    const description = await page.getAttribute('meta[name="description"]', 'content');
    expect(description?.length).toBeGreaterThan(10);

    const viewport = await page.getAttribute('meta[name="viewport"]', 'content');
    expect(viewport).toBeTruthy();
  });
});

test.describe('ROI Analytics - Core Features', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should display analytics dashboard sections', async ({ page }) => {
    // Main content area
    const mainContent = page.locator('main, [role="main"], .main-content');
    await expect(mainContent).toBeVisible();

    // Analytics sections should exist
    const sections = page.locator('section, [class*="analytics"], [class*="metric"]');
    const count = await sections.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have ROI metrics display', async ({ page }) => {
    const roiMetrics = page.locator('[class*="roi"], [class*="metric"], [class*="kpi"]');
    const count = await roiMetrics.count();

    // Should have at least some metric displays
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('should have chart/graph containers', async ({ page }) => {
    const charts = page.locator('canvas, svg, [class*="chart"], [id*="chart"]');
    const count = await charts.count();

    // Analytics page should have charts
    expect(count).toBeGreaterThanOrEqual(1);
  });
});

test.describe('ROI Analytics - Responsive', () => {
  const viewports = [
    { name: 'mobile', width: 375, height: 667 },
    { name: 'tablet', width: 768, height: 1024 },
    { name: 'desktop', width: 1440, height: 900 },
  ];

  for (const vp of viewports) {
    test(`should render correctly on ${vp.name} (${vp.width}x${vp.height})`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height });
      await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

      const mainContent = page.locator('main, [role="main"]');
      await expect(mainContent).toBeVisible();
    });
  }
});

test.describe('ROI Analytics - Data Tables', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/portal/roi-analytics.html', { waitUntil: 'domcontentloaded', timeout: 15000 });
    await page.waitForTimeout(2000);
  });

  test('should have data tables with proper structure', async ({ page }) => {
    const tables = page.locator('table, [class*="data-table"]');
    const count = await tables.count();

    if (count > 0) {
      const firstTable = tables.first();
      await expect(firstTable).toBeVisible();

      // Should have headers
      const headers = firstTable.locator('th, [class*="header"]');
      const headerCount = await headers.count();
      expect(headerCount).toBeGreaterThan(0);
    }
  });
});
