import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — UNTESSED PAGES COVERAGE TEST
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-14
 *
 * Coverage: 27 previously untested pages
 * ═══════════════════════════════════════════════════════════════════════════
 */

// Simple smoke test config - chromium only, short timeout
test.describe('Admin Pages - Previously Untested', () => {
  const ADMIN_PAGES = [
    { path: '/admin/ai-analysis.html', name: 'AI Analysis' },
    { path: '/admin/api-builder.html', name: 'API Builder' },
    { path: '/admin/approvals.html', name: 'Approvals' },
    { path: '/admin/binh-phap.html', name: 'Binh Phap' },
    { path: '/admin/community.html', name: 'Community' },
    { path: '/admin/content-calendar.html', name: 'Content Calendar' },
    { path: '/admin/customer-success.html', name: 'Customer Success' },
    { path: '/admin/deploy.html', name: 'Deploy' },
    { path: '/admin/docs.html', name: 'Docs' },
    { path: '/admin/ecommerce.html', name: 'Ecommerce' },
    { path: '/admin/events.html', name: 'Events' },
    { path: '/admin/index.html', name: 'Admin Index' },
    { path: '/admin/landing-builder.html', name: 'Landing Builder' },
    { path: '/admin/leads.html', name: 'Leads' },
    { path: '/admin/legal.html', name: 'Legal' },
    { path: '/admin/mvp-launch.html', name: 'MVP Launch' },
    { path: '/admin/onboarding.html', name: 'Admin Onboarding' },
    { path: '/admin/payments.html', name: 'Admin Payments' },
    { path: '/admin/pipeline.html', name: 'Pipeline' },
    { path: '/admin/retention.html', name: 'Retention' },
    { path: '/admin/roiaas-admin.html', name: 'ROIaaS Admin' },
    { path: '/admin/workflows.html', name: 'Workflows' },
  ];

  for (const page of ADMIN_PAGES) {
    test(`${page.name} loads successfully`, async ({ page: p }) => {
      const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 10000 });
      expect(response?.status()).toBe(200);

      const title = await p.title();
      expect(title.length).toBeGreaterThan(0);
    });
  }
});

test.describe('Affiliate Pages - Previously Untested', () => {
  const AFFILIATE_PAGES = [
    { path: '/affiliate/links.html', name: 'Affiliate Links' },
    { path: '/affiliate/settings.html', name: 'Affiliate Settings' },
  ];

  for (const page of AFFILIATE_PAGES) {
    test(`${page.name} loads successfully`, async ({ page: p }) => {
      const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 10000 });
      expect(response?.status()).toBe(200);

      const title = await p.title();
      expect(title.length).toBeGreaterThan(0);
    });
  }
});

test.describe('Portal Pages - Previously Untested', () => {
  const PORTAL_PAGES = [
    { path: '/portal/notifications.html', name: 'Portal Notifications' },
    { path: '/portal/ocop-catalog.html', name: 'OCOP Catalog' },
    { path: '/portal/roiaas-onboarding.html', name: 'ROIaaS Onboarding' },
  ];

  for (const page of PORTAL_PAGES) {
    test(`${page.name} loads successfully`, async ({ page: p }) => {
      const response = await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 10000 });
      expect(response?.status()).toBe(200);

      const title = await p.title();
      expect(title.length).toBeGreaterThan(0);
    });
  }
});

/**
 * AFFILIATE PAGES - Previously Untested
 */
test.describe('Affiliate Pages - Previously Untested', () => {
  const AFFILIATE_PAGES = [
    { path: '/affiliate/links.html', name: 'Affiliate Links', keywords: ['link', 'affiliate', 'referral'] },
    { path: '/affiliate/settings.html', name: 'Affiliate Settings', keywords: ['setting', 'config', 'profile'] },
  ];

  for (const page of AFFILIATE_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });

        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);

        const htmlLang = await p.getAttribute('html', 'lang');
        expect(htmlLang).toBeTruthy();

        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });

      test('has main content area', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 30000 });

        const hasMain = await p.locator('main, [role="main"], .main-content').count();
        expect(hasMain).toBeGreaterThan(0);
      });
    });
  }
});

/**
 * PORTAL PAGES - Previously Untested
 */
test.describe('Portal Pages - Previously Untested', () => {
  const PORTAL_PAGES = [
    { path: '/portal/notifications.html', name: 'Portal Notifications', keywords: ['notification', 'alert', 'message'] },
    { path: '/portal/ocop-catalog.html', name: 'OCOP Catalog', keywords: ['catalog', 'product', 'ocop'] },
    { path: '/portal/roiaas-onboarding.html', name: 'ROIaaS Onboarding', keywords: ['onboarding', 'roiaas', 'setup'] },
  ];

  for (const page of PORTAL_PAGES) {
    test.describe(`${page.name}`, () => {
      test('loads without critical errors', async ({ page: p }) => {
        const errors: string[] = [];

        p.on('pageerror', (error) => {
          if (error.message.includes('supabase') || error.message.includes('__ENV__')) return;
          if (/is not defined/.test(error.message) && /createDemo|Auth|mekongAgents/.test(error.message)) return;
          if (error.message.includes('CustomElementRegistry')) return;
          errors.push(error.message);
        });

        const response = await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });
        expect(response?.status()).toBe(200);
        expect(errors.length).toBeLessThanOrEqual(3);
      });

      test('has valid HTML structure', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'commit', timeout: 30000 });

        const hasDoctype = await p.evaluate(() => document.firstChild?.nodeType === 10);
        expect(hasDoctype).toBe(true);

        const htmlLang = await p.getAttribute('html', 'lang');
        expect(htmlLang).toBeTruthy();

        const title = await p.title();
        expect(title.length).toBeGreaterThan(0);
      });

      test('has main content area', async ({ page: p }) => {
        await p.goto(page.path, { waitUntil: 'domcontentloaded', timeout: 30000 });

        const hasMain = await p.locator('main, [role="main"], .main-content').count();
        expect(hasMain).toBeGreaterThan(0);
      });
    });
  }
});

/**
 * FUNCTIONAL TESTS - Specific Page Features
 */
test.describe('Functional Tests - Specific Pages', () => {
  test('AI Analysis page has analysis components', async ({ page }) => {
    await page.goto('/admin/ai-analysis.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/ai|analysis|insight|metric|analytics/i);
  });

  test('API Builder page has builder interface', async ({ page }) => {
    await page.goto('/admin/api-builder.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/api|builder|endpoint|method/i);
  });

  test('Approvals page has approval controls', async ({ page }) => {
    await page.goto('/admin/approvals.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/approval|pending|approve|reject/i);
  });

  test('Content Calendar page has calendar view', async ({ page }) => {
    await page.goto('/admin/content-calendar.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/calendar|schedule|date|post/i);
  });

  test('Deploy page has deployment controls', async ({ page }) => {
    await page.goto('/admin/deploy.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/deploy|build|release|version/i);
  });

  test('Ecommerce page has product management', async ({ page }) => {
    await page.goto('/admin/ecommerce.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/product|shop|order|ecommerce/i);
  });

  test('Landing Builder page has builder tools', async ({ page }) => {
    await page.goto('/admin/landing-builder.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/landing|builder|page|layout/i);
  });

  test('Leads page has lead management', async ({ page }) => {
    await page.goto('/admin/leads.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/lead|prospect|contact|email/i);
  });

  test('Pipeline page has sales pipeline', async ({ page }) => {
    await page.goto('/admin/pipeline.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/pipeline|sales|deal|stage/i);
  });

  test('Workflows page has workflow automation', async ({ page }) => {
    await page.goto('/admin/workflows.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/workflow|automation|flow|trigger/i);
  });

  test('Affiliate Links page has link management', async ({ page }) => {
    await page.goto('/affiliate/links.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/link|affiliate|referral|tracking/i);
  });

  test('OCOP Catalog page has product catalog', async ({ page }) => {
    await page.goto('/portal/ocop-catalog.html', { waitUntil: 'domcontentloaded', timeout: 15000 });

    const content = await page.content();
    expect(content.toLowerCase()).toMatch(/catalog|product|ocop|item/i);
  });
});

/**
 * ACCESSIBILITY TESTS - Previously Untested Pages
 */
test.describe('Accessibility Tests - Previously Untested', () => {
  const KEY_PAGES = [
    '/admin/ai-analysis.html',
    '/admin/api-builder.html',
    '/admin/content-calendar.html',
    '/admin/deploy.html',
    '/admin/ecommerce.html',
    '/admin/pipeline.html',
    '/admin/workflows.html',
  ];

  for (const pagePath of KEY_PAGES) {
    test(`${pagePath} has accessible landmarks`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });

      // Check for main landmark
      const hasMain = await page.locator('[role="main"], main').count();
      expect(hasMain).toBeGreaterThan(0);

      // Check for lang attribute
      const lang = await page.getAttribute('html', 'lang');
      expect(lang).toBeTruthy();
    });

    test(`${pagePath} has proper heading hierarchy`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });

      // Check h1 count (should be 0 or 1)
      const h1Count = await page.locator('h1').count();
      expect(h1Count).toBeLessThanOrEqual(1);
    });
  }
});

/**
 * RESPONSIVE TESTS - Mobile Viewports
 */
test.describe('Responsive Tests - Previously Untested Pages', () => {
  const VIEWPORTS = [
    { name: 'Mobile (375px)', width: 375, height: 667 },
    { name: 'Tablet (768px)', width: 768, height: 1024 },
    { name: 'Desktop (1024px)', width: 1024, height: 768 },
  ];

  const TEST_PAGES = [
    '/admin/ai-analysis.html',
    '/admin/content-calendar.html',
    '/admin/ecommerce.html',
    '/admin/pipeline.html',
  ];

  for (const pagePath of TEST_PAGES) {
    for (const viewport of VIEWPORTS) {
      test(`${pagePath} renders on ${viewport.name}`, async ({ page }) => {
        await page.setViewportSize({ width: viewport.width, height: viewport.height });
        await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });

        // Check page loads
        const content = await page.content();
        expect(content.length).toBeGreaterThan(100);
      });
    }
  }
});

/**
 * PERFORMANCE TESTS - Load Time
 */
test.describe('Performance Tests - Load Time', () => {
  const PAGES = [
    '/admin/ai-analysis.html',
    '/admin/api-builder.html',
    '/admin/content-calendar.html',
    '/admin/ecommerce.html',
    '/admin/pipeline.html',
  ];

  for (const pagePath of PAGES) {
    test(`${pagePath} loads within 3 seconds`, async ({ page }) => {
      const startTime = Date.now();
      const response = await page.goto(pagePath, { waitUntil: 'domcontentloaded', timeout: 10000 });
      const loadTime = Date.now() - startTime;

      expect(response?.status()).toBe(200);
      expect(loadTime).toBeLessThan(3000); // 3 second threshold
    });
  }
});
