import { test, expect } from '@playwright/test';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SADÉC MARKETING HUB — NEW UX FEATURES TEST
 *
 * Generated by: /dev-bug-sprint
 * Date: 2026-03-13
 *
 * Coverage: Tests for new UX features implemented in dev-feature command
 * - Command Palette (Ctrl+K)
 * - Notification Bell
 * - Theme Toggle (Dark Mode)
 * - Keyboard Shortcuts
 * - Error Boundaries
 *
 * Total: 15 test cases covering all new UX features
 * ═══════════════════════════════════════════════════════════════════════════
 */

test.describe('New UX Features', () => {
  // ============================================================================
  // COMMAND PALETTE (Ctrl+K)
  // ============================================================================

  test.describe('Command Palette', () => {
    test('command palette exists in DOM', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Command palette should exist
      const palette = page.locator('#command-palette, [role="dialog"][aria-label="Command Palette"]');
      await expect(palette).toBeVisible({ timeout: 5000 });
    });

    test('command palette opens with Ctrl+K', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Press Ctrl+K to open
      await page.keyboard.press('Control+KeyK');

      // Palette should be visible
      const palette = page.locator('.command-palette.open');
      await expect(palette).toBeVisible();

      // Input should be focused
      const input = page.locator('.command-palette-input');
      await expect(input).toBeFocused();
    });

    test('command palette has search input', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.keyboard.press('Control+KeyK');

      const input = page.locator('.command-palette-input');
      await expect(input).toHaveAttribute('placeholder', /Type a command|Search/i);
    });

    test('command palette shows results on search', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.keyboard.press('Control+KeyK');

      const input = page.locator('.command-palette-input');
      await input.fill('Dashboard');

      // Should show results
      const results = page.locator('.command-palette-item, .command-palette-results-list');
      await expect(results).toBeVisible();
    });

    test('command palette closes with Escape', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.keyboard.press('Control+KeyK');

      // Press Escape to close
      await page.keyboard.press('Escape');

      const palette = page.locator('.command-palette.open');
      await expect(palette).toBeHidden();
    });
  });

  // ============================================================================
  // NOTIFICATION BELL
  // ============================================================================

  test.describe('Notification Bell', () => {
    test('notification bell exists in header', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      const bell = page.locator('#notification-bell, .notification-bell');
      await expect(bell).toBeVisible();
    });

    test('notification bell has badge for unread count', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      const badge = page.locator('.notification-badge');
      // Badge may be hidden if no unread notifications
      await expect(badge).toBeVisible({ timeout: 3000 });
    });

    test('notification panel opens on click', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      const bell = page.locator('.notification-bell');
      await bell.click();

      const panel = page.locator('.notification-panel');
      await expect(panel).toBeVisible();
    });

    test('notification panel has header with actions', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.locator('.notification-bell').click();

      const header = page.locator('.notification-panel-header');
      await expect(header).toBeVisible();

      // Should have mark all as read button
      const markAllRead = page.locator('.mark-all-read-btn');
      await expect(markAllRead).toBeVisible();
    });

    test('notification panel shows empty state when no notifications', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.locator('.notification-bell').click();

      // Either has notifications or shows empty state
      const emptyState = page.locator('.notification-empty');
      const notificationList = page.locator('.notification-list');

      const emptyVisible = await emptyState.isVisible();
      const listVisible = await notificationList.isVisible();

      expect(emptyVisible || listVisible).toBeTruthy();
    });
  });

  // ============================================================================
  // THEME TOGGLE (DARK MODE)
  // ============================================================================

  test.describe('Theme Toggle', () => {
    test('theme toggle button exists in header', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      const toggle = page.locator('#theme-toggle, .theme-toggle, button[aria-label="Toggle dark mode"]');
      await expect(toggle).toBeVisible();
    });

    test('theme toggle switches between light and dark mode', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Get initial theme
      const html = page.locator('html');
      const initialTheme = await html.getAttribute('data-theme');

      // Click toggle
      const toggle = page.locator('#theme-toggle, .theme-toggle').first();
      await toggle.click();

      // Wait for theme change
      await page.waitForTimeout(500);

      // Check theme changed
      const newTheme = await html.getAttribute('data-theme');
      expect(initialTheme !== newTheme).toBeTruthy();
    });

    test('dark mode applies dark theme styles', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Switch to dark mode
      const toggle = page.locator('#theme-toggle, .theme-toggle').first();
      await toggle.click();
      await page.waitForTimeout(500);

      // Check dark mode class
      const html = page.locator('html');
      const hasDarkClass = await html.classList().then(classes =>
        classes.includes('dark-mode')
      ).catch(() => false);

      // Or check data-theme attribute
      const dataTheme = await html.getAttribute('data-theme');

      expect(hasDarkClass || dataTheme === 'dark').toBeTruthy();
    });
  });

  // ============================================================================
  // KEYBOARD SHORTCUTS
  // ============================================================================

  test.describe('Keyboard Shortcuts', () => {
    test('keyboard shortcuts help modal opens with Ctrl+?', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Press Ctrl+? to open help
      await page.keyboard.press('Control+Shift+Slash');

      // Help modal should appear
      const modal = page.locator('#keyboard-help-modal, .keyboard-help-modal');
      await expect(modal).toBeVisible({ timeout: 3000 });
    });

    test('help modal shows shortcuts list', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.keyboard.press('Control+Shift+Slash');

      const shortcutsList = page.locator('.shortcuts-list, .shortcuts-grid');
      await expect(shortcutsList).toBeVisible();
    });

    test('help modal closes with Escape', async ({ page }) => {
      await page.goto('/admin/dashboard.html');
      await page.keyboard.press('Control+Shift+Slash');
      await page.keyboard.press('Escape');

      const modal = page.locator('#keyboard-help-modal[open]');
      await expect(modal).toBeHidden();
    });
  });

  // ============================================================================
  // ERROR BOUNDARIES
  // ============================================================================

  test.describe('Error Boundaries', () => {
    test('error boundary styles are loaded', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Check if error-boundary CSS is loaded
      const errorBoundaryStyle = await page.evaluate(() => {
        const styles = Array.from(document.styleSheets);
        for (const sheet of styles) {
          try {
            const rules = Array.from(sheet.cssRules || []);
            for (const rule of rules) {
              if (rule.cssText.includes('.error-boundary')) {
                return true;
              }
            }
          } catch (e) {
            // Cross-origin stylesheets may throw
          }
        }
        return false;
      });

      expect(errorBoundaryStyle).toBeTruthy();
    });

    test('empty state component is available', async ({ page }) => {
      await page.goto('/admin/dashboard.html');

      // Check if empty-state styles are loaded
      const emptyStateStyle = await page.evaluate(() => {
        const styles = Array.from(document.styleSheets);
        for (const sheet of styles) {
          try {
            const rules = Array.from(sheet.cssRules || []);
            for (const rule of rules) {
              if (rule.cssText.includes('.empty-state')) {
                return true;
              }
            }
          } catch (e) {
            // Cross-origin stylesheets may throw
          }
        }
        return false;
      });

      expect(emptyStateStyle).toBeTruthy();
    });
  });
});
