import { test, expect } from '@playwright/test';

/**
 * Widget Components Coverage Tests
 *
 * Mục tiêu: Cover 4 widget components còn thiếu coverage
 * - conversion-funnel.html
 * - global-search.html
 * - notification-bell.html
 * - theme-toggle.html
 *
 * Generated by: /dev:bug-sprint
 * Date: 2026-03-14
 */

test.describe('Conversion Funnel Widget', () => {
  test('should load conversion funnel widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title).toContain('Conversion Funnel');
  });

  test('should render funnel widget container', async ({ page }) => {
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    const funnelWidget = page.locator('.conversion-funnel-widget');
    await expect(funnelWidget).toBeVisible();
  });

  test('should have funnel header and title', async ({ page }) => {
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    const header = page.locator('.funnel-header');
    await expect(header).toBeVisible();

    const title = page.locator('.funnel-title');
    await expect(title).toBeVisible();
  });

  test('should have funnel stages', async ({ page }) => {
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    const stagesContainer = page.locator('.funnel-stages');
    await expect(stagesContainer).toBeVisible();
  });

  test('should be responsive on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    const funnelWidget = page.locator('.conversion-funnel-widget');
    await expect(funnelWidget).toBeVisible();
  });
});

test.describe('Global Search Widget', () => {
  test('should load global search widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title).toContain('Global Search');
  });

  test('should render search widget container', async ({ page }) => {
    await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    const searchWidget = page.locator('.global-search-widget');
    await expect(searchWidget).toBeVisible();
  });

  test('should have search trigger button with Ctrl+K shortcut', async ({ page }) => {
    await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'domcontentloaded'
    });

    const searchBtn = page.locator('#search-trigger-btn');
    await expect(searchBtn).toBeVisible();

    // Check for Ctrl+K shortcut in title or aria-label
    const title = await searchBtn.getAttribute('title');
    expect(title).toContain('Ctrl+K');
  });

  test('should have search modal with input', async ({ page }) => {
    await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'domcontentloaded'
    });

    const searchModal = page.locator('#search-modal');
    await expect(searchModal).toHaveCount({ gte: 0 });

    const searchInput = page.locator('#search-input, .search-input');
    await expect(searchInput).toHaveCount({ gte: 0 });
  });
});

test.describe('Notification Bell Widget', () => {
  test('should load notification bell widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title).toContain('Notification');
  });

  test('should render notification bell container', async ({ page }) => {
    await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    const bellWidget = page.locator('.notification-bell-widget, [class*="notification-bell"]');
    await expect(bellWidget).toHaveCount({ gte: 0 });
  });

  test('should have notification badge element', async ({ page }) => {
    await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'domcontentloaded'
    });

    const badge = page.locator('[class*="badge"], [class*="count"], .notification-count');
    await expect(badge).toHaveCount({ gte: 0 });
  });

  test('should have notification dropdown panel', async ({ page }) => {
    await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'domcontentloaded'
    });

    const panel = page.locator('[class*="dropdown"], [class*="panel"], .notification-panel');
    await expect(panel).toHaveCount({ gte: 0 });
  });
});

test.describe('Theme Toggle Widget', () => {
  test('should load theme toggle widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title.toLowerCase()).toContain('theme');
  });

  test('should render theme toggle button', async ({ page }) => {
    await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    const toggleBtn = page.locator('#theme-toggle-btn, .theme-toggle-btn');
    await expect(toggleBtn).toBeVisible();
  });

  test('should have theme dropdown menu', async ({ page }) => {
    await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'domcontentloaded'
    });

    const dropdown = page.locator('#theme-dropdown, .theme-dropdown');
    await expect(dropdown).toHaveCount({ gte: 0 });
  });

  test('should have light/dark theme options', async ({ page }) => {
    await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'domcontentloaded'
    });

    const body = page.locator('body');
    const text = await body.innerText();
    expect(text.toLowerCase()).toMatch(/light|dark|theme/i);
  });
});

test.describe('All Widgets - Integration Tests', () => {
  test('should load all widgets on dashboard', async ({ page }) => {
    const response = await page.goto('/admin/dashboard.html', {
      waitUntil: 'load',
      timeout: 20000
    });

    expect(response?.status()).toBe(200);

    await page.waitForTimeout(2000);

    const kpiCards = page.locator('kpi-card-widget, [class*="kpi-card"]');
    await expect(kpiCards).toHaveCount({ gte: 1 });
  });

  test('should have no console errors when loading widgets', async ({ page }) => {
    const errors: string[] = [];

    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        const text = msg.text();
        if (text.includes('supabase')) return;
        if (text.includes('__ENV__')) return;
        if (text.includes('CustomElementRegistry')) return;
        errors.push(text);
      }
    });

    await page.goto('/admin/widgets-demo.html', {
      waitUntil: 'load',
      timeout: 20000
    });

    await page.waitForTimeout(1000);

    expect(errors.length, `Console errors: ${errors.join(', ')}`).toBe(0);
  });
});
