import { test, expect } from '@playwright/test';

/**
 * Widget Components Coverage Tests
 *
 * Mục tiêu: Cover 4 widget components còn thiếu coverage
 * - conversion-funnel.html
 * - global-search.html
 * - notification-bell.html
 * - theme-toggle.html
 *
 * Generated by: /dev:bug-sprint
 * Date: 2026-03-14
 */

test.describe('Conversion Funnel Widget', () => {
  test('should load conversion funnel widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title).toContain('Conversion Funnel');
  });

  test('should render funnel widget container', async ({ page }) => {
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    // Wait for custom elements to render
    await page.waitForTimeout(500);

    // Main widget container should exist
    const funnelWidget = page.locator('.conversion-funnel-widget');
    await expect(funnelWidget).toBeVisible();
  });

  test('should have funnel header and title', async ({ page }) => {
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    // Header should exist
    const header = page.locator('.funnel-header');
    await expect(header).toBeVisible();

    // Title should exist
    const title = page.locator('.funnel-title');
    await expect(title).toBeVisible();
    await expect(title).toContainText('chuyển đổi');
  });

  test('should have funnel stages', async ({ page }) => {
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    // Funnel should have stages container
    const stagesContainer = page.locator('.funnel-stages');
    await expect(stagesContainer).toBeVisible();
  });

  test('should be responsive on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/admin/widgets/conversion-funnel.html', {
      waitUntil: 'domcontentloaded'
    });

    const funnelWidget = page.locator('.conversion-funnel-widget');
    await expect(funnelWidget).toBeVisible();
  });
});

test.describe('Global Search Widget', () => {
  test('should load global search widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title).toContain('Global Search');
  });

  test('should render search widget container', async ({ page }) => {
    await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    // Main widget container
    const searchWidget = page.locator('.global-search-widget, [class*="search-widget"]');
    await expect(searchWidget).toBeVisible();
  });

  test('should have search input field', async ({ page }) => {
    await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'domcontentloaded'
    });

    // Search input should exist
    const searchInput = page.locator('input[type="search"], input[placeholder*="Tìm"], input[class*="search-input"]');
    await expect(searchInput).toBeVisible();
  });

  test('should have keyboard shortcut hint', async ({ page }) => {
    await page.goto('/admin/widgets/global-search.html', {
      waitUntil: 'domcontentloaded'
    });

    // Should mention Ctrl+K or Cmd+K shortcut
    const body = page.locator('body');
    const text = await body.innerText();
    expect(text.toLowerCase()).toMatch(/ctrl\+?k|cmd\+?k|⌘k/i);
  });
});

test.describe('Notification Bell Widget', () => {
  test('should load notification bell widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title).toContain('Notification');
  });

  test('should render notification bell container', async ({ page }) => {
    await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    // Bell icon should exist
    const bellIcon = page.locator('[class*="bell"], .notification-bell, bell-icon');
    await expect(bellIcon).toBeVisible();
  });

  test('should have notification badge element', async ({ page }) => {
    await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'domcontentloaded'
    });

    // Badge should exist (even if hidden when count=0)
    const badge = page.locator('[class*="badge"], [class*="count"], .notification-count');
    await expect(badge).toHaveCount({ gte: 0 });
  });

  test('should have notification dropdown/panel', async ({ page }) => {
    await page.goto('/admin/widgets/notification-bell.html', {
      waitUntil: 'domcontentloaded'
    });

    // Dropdown panel should exist in DOM
    const panel = page.locator('[class*="dropdown"], [class*="panel"], .notification-panel');
    await expect(panel).toHaveCount({ gte: 0 });
  });
});

test.describe('Theme Toggle Widget', () => {
  test('should load theme toggle widget page', async ({ page }) => {
    const response = await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'load',
      timeout: 15000
    });

    expect(response?.status()).toBe(200);

    const title = await page.title();
    expect(title.toLowerCase()).toContain('theme');
  });

  test('should render theme toggle button', async ({ page }) => {
    await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'domcontentloaded'
    });

    await page.waitForTimeout(500);

    // Toggle button should exist
    const toggleBtn = page.locator('[class*="theme-toggle"], button[aria-label*="theme"], .theme-switch');
    await expect(toggleBtn).toBeVisible();
  });

  test('should have icon for light/dark modes', async ({ page }) => {
    await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'domcontentloaded'
    });

    // Should have sun/moon icons or similar
    const body = page.locator('body');
    const text = await body.innerText();
    // Check for theme-related text or icons
    expect(text.toLowerCase()).toMatch(/theme|dark|light|sun|moon/i);
  });

  test('should persist theme preference', async ({ page }) => {
    await page.goto('/admin/widgets/theme-toggle.html', {
      waitUntil: 'domcontentloaded'
    });

    // Click toggle button
    const toggleBtn = page.locator('[class*="theme-toggle"], button[aria-label*="theme"]').first();
    if (await toggleBtn.isVisible()) {
      await toggleBtn.click();
      await page.waitForTimeout(300);

      // Check localStorage for theme preference
      const theme = await page.evaluate(() => localStorage.getItem('theme'));
      expect(theme).toMatch(/light|dark/i);
    }
  });
});

test.describe('All Widgets - Integration Tests', () => {
  test('should load all widgets on dashboard', async ({ page }) => {
    const response = await page.goto('/admin/dashboard.html', {
      waitUntil: 'load',
      timeout: 20000
    });

    expect(response?.status()).toBe(200);

    await page.waitForTimeout(2000);

    // Check for widget containers
    const kpiCards = page.locator('kpi-card-widget, [class*="kpi-card"]');
    await expect(kpiCards).toHaveCount({ gte: 1 });
  });

  test('should have no console errors when loading widgets', async ({ page }) => {
    const errors: string[] = [];

    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        const text = msg.text();
        // Ignore benign errors
        if (text.includes('supabase')) return;
        if (text.includes('__ENV__')) return;
        if (text.includes('CustomElementRegistry')) return;
        errors.push(text);
      }
    });

    await page.goto('/admin/widgets-demo.html', {
      waitUntil: 'load',
      timeout: 20000
    });

    await page.waitForTimeout(1000);

    expect(errors.length, `Console errors: ${errors.join(', ')}`).toBe(0);
  });
});
