#!/usr/bin/env node
/**
 * inject-env.js - Build-time environment variable injection
 * Sa Đéc Marketing Hub - Security Hardening Phase 1
 * 
 * This script generates env.js with Supabase credentials from environment variables.
 * Run this script during the Vercel build process.
 * 
 * Usage:
 *   SUPABASE_URL=xxx SUPABASE_ANON_KEY=yyy node inject-env.js
 */

const fs = require('fs');
const path = require('path');

// Read from environment variables
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

// Validate required variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn('⚠️  Warning: SUPABASE_URL or SUPABASE_ANON_KEY not set.');
    console.warn('   The app will fall back to demo mode.');
}

// Generate the env.js content
const content = `// Auto-generated by inject-env.js during build
// DO NOT COMMIT THIS FILE TO VERSION CONTROL
window.__ENV__ = {
  SUPABASE_URL: "${SUPABASE_URL}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
  BUILD_TIME: "${new Date().toISOString()}"
};
`;

// Write to the root directory
const outputPath = path.join(__dirname, 'env.js');
fs.writeFileSync(outputPath, content, 'utf8');

console.log('✅ env.js generated successfully');
console.log(`   SUPABASE_URL: ${SUPABASE_URL ? '***' + SUPABASE_URL.slice(-10) : '(not set)'}`);
console.log(`   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY ? '***' + SUPABASE_ANON_KEY.slice(-10) : '(not set)'}`);
