#!/usr/bin/env node
/**
 * Markdown Report Generator
 */

/**
 * Generate markdown report
 */
function generateMarkdownReport(results) {
    const timestamp = new Date(results.timestamp).toLocaleString('vi-VN');

    let report = `# 🔍 Audit Report — Sa Đéc Marketing Hub

**Date:** ${timestamp}
**Files Scanned:** ${results.filesScanned}

---

## 📊 Summary

| Check | Issues | Status |
|-------|--------|--------|
| Broken Links | ${results.links.broken.length} | ${results.links.broken.length === 0 ? '✅ Pass' : '❌ Fix Needed'} |
| Missing Meta Tags | ${results.meta.missing.length} | ${results.meta.missing.length === 0 ? '✅ Pass' : '⚠️ Review'} |
| Accessibility Issues | ${results.a11y.issues.length} | ${results.a11y.issues.length === 0 ? '✅ Pass' : '❌ Fix Needed'} |
| Duplicate IDs | ${results.ids.duplicates.length} | ${results.ids.duplicates.length === 0 ? '✅ Pass' : '❌ Fix Needed'} |

---

## 🔗 Broken Links

${results.links.broken.length === 0 ? '✅ No broken links found!' : generateBrokenLinksTable(results.links)}

---

## 🏷️ Missing Meta Tags

${results.meta.missing.length === 0 ? '✅ All meta tags present!' : generateMetaTagsTable(results.meta)}

---

## ♿ Accessibility Issues

${results.a11y.issues.length === 0 ? '✅ No accessibility issues found!' : generateA11yTable(results.a11y)}

---

## 🔢 Duplicate IDs

${results.ids.duplicates.length === 0 ? '✅ No duplicate IDs found!' : generateIDsTable(results.ids)}

---

## 📈 Health Score

${calculateScore(results)}/100 ${getScoreEmoji(calculateScore(results))}

---

*Generated by Mekong CLI Audit Framework*
`;

    return report;
}

function generateBrokenLinksTable(links) {
    if (links.broken.length === 0) return 'No broken links.';

    let table = '| File | Link | Line |\n|------|------|------|\n';
    for (const issue of links.broken.slice(0, 20)) {
        table += `| ${issue.file} | ${issue.href} | ${issue.line || 'N/A'} |\n`;
    }
    if (links.broken.length > 20) {
        table += `\n*... and ${links.broken.length - 20} more*`;
    }
    return table;
}

function generateMetaTagsTable(meta) {
    if (meta.missing.length === 0) return 'No missing meta tags.';

    let table = '| File | Missing Tag | Severity |\n|------|-------------|----------|\n';
    for (const issue of meta.missing.slice(0, 20)) {
        const severity = issue.severity === 'error' ? '🔴 Required' : '🟡 Recommended';
        table += `| ${issue.file} | ${issue.tag} | ${severity} |\n`;
    }
    if (meta.missing.length > 20) {
        table += `\n*... and ${meta.missing.length - 20} more*`;
    }
    return table;
}

function generateA11yTable(a11y) {
    if (a11y.issues.length === 0) return 'No accessibility issues.';

    let table = '| File | Issue | Type | Suggestion |\n|------|-------|------|------------|\n';
    for (const issue of a11y.issues.slice(0, 20)) {
        table += `| ${issue.file} | ${issue.message.substring(0, 50)}... | ${issue.type} | ${issue.suggestion || 'Manual fix'} |\n`;
    }
    if (a11y.issues.length > 20) {
        table += `\n*... and ${a11y.issues.length - 20} more*`;
    }
    return table;
}

function generateIDsTable(ids) {
    if (ids.duplicates.length === 0) return 'No duplicate IDs.';

    let table = '| File | Duplicate ID | Count |\n|------|--------------|-------|\n';
    for (const dup of ids.duplicates.slice(0, 20)) {
        table += `| ${dup.file} | ${dup.id} | ${dup.count} |\n`;
    }
    if (ids.duplicates.length > 20) {
        table += `\n*... and ${ids.duplicates.length - 20} more*`;
    }
    return table;
}

function calculateScore(results) {
    const totalIssues =
        results.links.broken.length +
        results.meta.missing.length +
        results.a11y.issues.length +
        results.ids.duplicates.length;

    // Deduct points: 2 points per issue
    return Math.max(0, Math.min(100, 100 - (totalIssues * 2)));
}

function getScoreEmoji(score) {
    if (score >= 90) return '🟢 Excellent';
    if (score >= 70) return '🟡 Good';
    if (score >= 50) return '🟠 Fair';
    return '🔴 Poor';
}

module.exports = { generateMarkdownReport, calculateScore, getScoreEmoji };
